export const events = new Map([
  [
    '5560',
    {
      kind: 'event',
      id: '5560',
      label: 'Wedding of Richard Beer-Hofmann and Paula Lissy',
      persons: new Set(['622', '470']),
      places: new Set([]),
      institutions: new Set([]),
      events: new Set([]),
    },
  ],
  [
    '5586',
    {
      kind: 'event',
      id: '5586',
      label: 'Journey through the Alps',
      persons: new Set(['622', '470']),
      places: new Set([]),
      institutions: new Set([]),
      events: new Set([]),
    },
  ],
  [
    '1555',
    {
      kind: 'event',
      id: '1555',
      label: "Thompson's and Lewis's Christmas Party",
      persons: new Set(['546', '387', '520', '425', '448', '466']),
      places: new Set(['1456']),
      institutions: new Set([]),
      events: new Set([]),
    },
  ],
  [
    '5236',
    {
      kind: 'event',
      id: '5236',
      label:
        'the second attempt by Emperor Karl and his wife Zita to return from Switzerland and reclaim the crown of Hungary',
      persons: new Set(['546']),
      places: new Set([]),
      institutions: new Set([]),
      events: new Set([]),
    },
  ],
  [
    '5238',
    {
      kind: 'event',
      id: '5238',
      label: 'the food riots  in Vienna on 1 December 1921',
      persons: new Set(['546']),
      places: new Set([]),
      institutions: new Set([]),
      events: new Set([]),
    },
  ],
  [
    '5242',
    {
      kind: 'event',
      id: '5242',
      label:
        'a meeting between Dorothy Thompson, Carl and Alice Zuckmayer and Eugenia Schwarzwald in Berlin',
      persons: new Set(['546', '474', '633']),
      places: new Set(['1107']),
      institutions: new Set([]),
      events: new Set([]),
    },
  ],
  [
    '7081',
    {
      kind: 'event',
      id: '7081',
      label: 'Austrian Civil War',
      persons: new Set(['546', '520', '7378']),
      places: new Set([]),
      institutions: new Set([]),
      events: new Set([]),
    },
  ],
  [
    '5119',
    {
      kind: 'event',
      id: '5119',
      label: 'the Brecht-boycott',
      persons: new Set(['608', '610']),
      places: new Set([]),
      institutions: new Set([]),
      events: new Set([]),
    },
  ],
  [
    '6488',
    {
      kind: 'event',
      id: '6488',
      label: 'Jedermann at the Salzburg Festival',
      persons: new Set(['616']),
      places: new Set(['1423']),
      institutions: new Set([]),
      events: new Set([]),
    },
  ],
  [
    '8064',
    {
      kind: 'event',
      id: '8064',
      label: 'Rosalinda (Die Fledermaus)',
      persons: new Set(['676', '2699']),
      places: new Set([]),
      institutions: new Set([]),
      events: new Set([]),
    },
  ],
  [
    '5763',
    {
      kind: 'event',
      id: '5763',
      label: 'Concert of Jean Starr Untermeyer in Vienna',
      persons: new Set(['492', '470']),
      places: new Set([]),
      institutions: new Set([]),
      events: new Set([]),
    },
  ],
  [
    '4878',
    {
      kind: 'event',
      id: '4878',
      label: 'Goethe Bicentennial Convocation and Music Festival',
      persons: new Set(['672']),
      places: new Set(['4879']),
      institutions: new Set([]),
      events: new Set([]),
    },
  ],
  [
    '4906',
    {
      kind: 'event',
      id: '4906',
      label: 'Early reading from working draft of "The Woman of Andros"',
      persons: new Set(['672']),
      places: new Set(['177']),
      institutions: new Set([]),
      events: new Set([]),
    },
  ],
  [
    '4949',
    {
      kind: 'event',
      id: '4949',
      label: "Promotion tour for German translations of Thornton Wilder's books",
      persons: new Set(['672', '577']),
      places: new Set(['1107']),
      institutions: new Set([]),
      events: new Set([]),
    },
  ],
  [
    '4965',
    {
      kind: 'event',
      id: '4965',
      label: 'class in symphony conducting',
      persons: new Set(['672']),
      places: new Set([]),
      institutions: new Set([]),
      events: new Set([]),
    },
  ],
  [
    '4913',
    {
      kind: 'event',
      id: '4913',
      label: 'Lecture on Thornton Wilder at the Volkshochschule Ottakring',
      persons: new Set(['577']),
      places: new Set(['177']),
      institutions: new Set([]),
      events: new Set([]),
    },
  ],
  [
    '2472',
    {
      kind: 'event',
      id: '2472',
      label: 'Nazi propaganda activity 1933-05-01',
      persons: new Set(['1530']),
      places: new Set([]),
      institutions: new Set([]),
      events: new Set([]),
    },
  ],
  [
    '5170',
    {
      kind: 'event',
      id: '5170',
      label: 'opera performances at the Wiener Staatsoper',
      persons: new Set(['1530']),
      places: new Set([]),
      institutions: new Set([]),
      events: new Set([]),
    },
  ],
  [
    '5172',
    {
      kind: 'event',
      id: '5172',
      label: 'psychoanalytic treatment by Sigmund Freud',
      persons: new Set(['1530']),
      places: new Set([]),
      institutions: new Set([]),
      events: new Set([]),
    },
  ],
  [
    '5220',
    {
      kind: 'event',
      id: '5220',
      label: 'regular meetings with journalists at Café Louvre',
      persons: new Set(['520', '6561']),
      places: new Set([]),
      institutions: new Set([]),
      events: new Set([]),
    },
  ],
  [
    '5222',
    {
      kind: 'event',
      id: '5222',
      label: 'regular encounters with politicians and cultural pundits in Vienna',
      persons: new Set(['520']),
      places: new Set([]),
      institutions: new Set([]),
      events: new Set([]),
    },
  ],
  [
    '6330',
    {
      kind: 'event',
      id: '6330',
      label: "John Gunther's regular luncheons at Rathauskeller for selected guests",
      persons: new Set(['520', '1623', '6328', '6334', '466']),
      places: new Set(['6325']),
      institutions: new Set([]),
      events: new Set([]),
    },
  ],
  [
    '5232',
    {
      kind: 'event',
      id: '5232',
      label: 'the brutality of the Nazi mob directed against Jews after the Anschluss',
      persons: new Set(['523']),
      places: new Set([]),
      institutions: new Set([]),
      events: new Set([]),
    },
  ],
  [
    '5234',
    {
      kind: 'event',
      id: '5234',
      label: 'detailed insights into Viennese life through his Viennese wife',
      persons: new Set(['523']),
      places: new Set([]),
      institutions: new Set([]),
      events: new Set([]),
    },
  ],
  [
    '5265',
    {
      kind: 'event',
      id: '5265',
      label: 'anti-Fascist activities',
      persons: new Set(['7378']),
      places: new Set([]),
      institutions: new Set([]),
      events: new Set([]),
    },
  ],
  [
    '5281',
    {
      kind: 'event',
      id: '5281',
      label: 'the controversy between Mary McCarthy and Lillian Hellman',
      persons: new Set(['7378']),
      places: new Set([]),
      institutions: new Set([]),
      events: new Set([]),
    },
  ],
  [
    '2429',
    {
      kind: 'event',
      id: '2429',
      label: 'opera performance 1933-05-26',
      persons: new Set(['358']),
      places: new Set([]),
      institutions: new Set([]),
      events: new Set([]),
    },
  ],
  [
    '2467',
    {
      kind: 'event',
      id: '2467',
      label: 'opera performance 1933-05-12',
      persons: new Set(['358']),
      places: new Set([]),
      institutions: new Set([]),
      events: new Set([]),
    },
  ],
  [
    '2220',
    {
      kind: 'event',
      id: '2220',
      label: 'opera performance 1924-04-27',
      persons: new Set(['504']),
      places: new Set([]),
      institutions: new Set([]),
      events: new Set([]),
    },
  ],
  [
    '2285',
    {
      kind: 'event',
      id: '2285',
      label: 'opera performance 1924-04-04',
      persons: new Set(['504']),
      places: new Set([]),
      institutions: new Set([]),
      events: new Set([]),
    },
  ],
  [
    '2288',
    {
      kind: 'event',
      id: '2288',
      label: 'opera performance 1924-04-08',
      persons: new Set(['504']),
      places: new Set([]),
      institutions: new Set([]),
      events: new Set([]),
    },
  ],
  [
    '2291',
    {
      kind: 'event',
      id: '2291',
      label: 'opera performance 1924-04-20',
      persons: new Set(['504']),
      places: new Set([]),
      institutions: new Set([]),
      events: new Set([]),
    },
  ],
  [
    '2294',
    {
      kind: 'event',
      id: '2294',
      label: 'concert 1924-04-11',
      persons: new Set(['504']),
      places: new Set([]),
      institutions: new Set([]),
      events: new Set([]),
    },
  ],
  [
    '2310',
    {
      kind: 'event',
      id: '2310',
      label: 'opera performance 1924-04-02',
      persons: new Set(['504']),
      places: new Set([]),
      institutions: new Set([]),
      events: new Set([]),
    },
  ],
  [
    '2348',
    {
      kind: 'event',
      id: '2348',
      label: 'concert with Amato and Piccaver',
      persons: new Set(['504']),
      places: new Set([]),
      institutions: new Set([]),
      events: new Set([]),
    },
  ],
  [
    '6127',
    {
      kind: 'event',
      id: '6127',
      label: 'Zionist World Congress',
      persons: new Set(['426']),
      places: new Set([]),
      institutions: new Set([]),
      events: new Set([]),
    },
  ],
  [
    '7569',
    {
      kind: 'event',
      id: '7569',
      label: "Sunday's at Salka",
      persons: new Set(['834']),
      places: new Set(['5960']),
      institutions: new Set([]),
      events: new Set([]),
    },
  ],
  [
    '8075',
    {
      kind: 'event',
      id: '8075',
      label: 'Die schöne Helena',
      persons: new Set(['2699']),
      places: new Set([]),
      institutions: new Set([]),
      events: new Set([]),
    },
  ],
  [
    '3918',
    {
      kind: 'event',
      id: '3918',
      label: 'Pola Red Sea expeditions',
      persons: new Set(['3083']),
      places: new Set([]),
      institutions: new Set([]),
      events: new Set([]),
    },
  ],
  [
    '3957',
    {
      kind: 'event',
      id: '3957',
      label: 'Hassler Expedition',
      persons: new Set(['3083']),
      places: new Set([
        '3130',
        '2530',
        '3981',
        '3989',
        '4249',
        '4253',
        '3991',
        '3993',
        '3995',
        '4011',
      ]),
      institutions: new Set([]),
      events: new Set([]),
    },
  ],
  [
    '4046',
    {
      kind: 'event',
      id: '4046',
      label: 'Centenary Celebrations of Charles Darwin’s birthday',
      persons: new Set(['3083']),
      places: new Set([]),
      institutions: new Set([]),
      events: new Set([]),
    },
  ],
  [
    '5306',
    {
      kind: 'event',
      id: '5306',
      label:
        'interviews with leading artists in the field of classical music and politicians (Jimmy Berg)',
      persons: new Set(['5377']),
      places: new Set([]),
      institutions: new Set([]),
      events: new Set([]),
    },
  ],
])
