export const institutions = new Map([
  [
    '765',
    {
      kind: 'institution',
      id: '765',
      label: 'University of Vienna',
      persons: new Set([
        '1079',
        '7526',
        '7531',
        '8130',
        '767',
        '2085',
        '2090',
        '1150',
        '2061',
        '6811',
        '7664',
        '7971',
        '7496',
        '7497',
        '6817',
        '1689',
        '2153',
        '2155',
        '959',
        '960',
        '5191',
        '5202',
        '5203',
        '8131',
        '7073',
        '3154',
        '6862',
        '6863',
        '7920',
        '7921',
      ]),
      places: new Set(['766']),
      institutions: new Set([]),
      events: new Set([]),
    },
  ],
  [
    '982',
    {
      kind: 'institution',
      id: '982',
      label: 'American citizenship',
      persons: new Set([
        '1088',
        '1128',
        '983',
        '6033',
        '2631',
        '2018',
        '7369',
        '7373',
        '7371',
        '7368',
        '7722',
        '2008',
        '7865',
        '7966',
        '5525',
        '1232',
        '7376',
        '7374',
        '7375',
        '7370',
      ]),
      places: new Set([]),
      institutions: new Set([]),
      events: new Set([]),
    },
  ],
  [
    '2839',
    {
      kind: 'institution',
      id: '2839',
      label: 'Junge Wien',
      persons: new Set(['2840']),
      places: new Set([]),
      institutions: new Set([]),
      events: new Set([]),
    },
  ],
  [
    '1145',
    {
      kind: 'institution',
      id: '1145',
      label: 'Jewish',
      persons: new Set(['5031', '2014', '2064', '1147', '2060', '1303', '5056']),
      places: new Set([]),
      institutions: new Set([]),
      events: new Set([]),
    },
  ],
  [
    '592',
    {
      kind: 'institution',
      id: '592',
      label: 'Theater in der Josefstadt',
      persons: new Set(['5034', '7248', '7249', '694', '2013', '6948']),
      places: new Set(['593', '595', '6894']),
      institutions: new Set([]),
      events: new Set([]),
    },
  ],
  [
    '716',
    {
      kind: 'institution',
      id: '716',
      label: 'Burgtheater Wien',
      persons: new Set(['5035', '659', '7242', '695', '6874', '2902', '7321', '2152', '6277']),
      places: new Set(['717', '6873']),
      institutions: new Set([]),
      events: new Set([]),
    },
  ],
  [
    '5551',
    {
      kind: 'institution',
      id: '5551',
      label: 'Pension "Jägerhof"',
      persons: new Set(['5554']),
      places: new Set(['5553']),
      institutions: new Set([]),
      events: new Set([]),
    },
  ],
  [
    '1033',
    {
      kind: 'institution',
      id: '1033',
      label: 'Café Herrenhof',
      persons: new Set(['6424', '1045', '1041', '1042', '1805', '1806']),
      places: new Set(['1034', '1050']),
      institutions: new Set([]),
      events: new Set([]),
    },
  ],
  [
    '1871',
    {
      kind: 'institution',
      id: '1871',
      label: 'British citizenship',
      persons: new Set(['1872']),
      places: new Set([]),
      institutions: new Set([]),
      events: new Set([]),
    },
  ],
  [
    '1680',
    {
      kind: 'institution',
      id: '1680',
      label: 'Hotel Regina',
      persons: new Set(['6878', '1684', '5174']),
      places: new Set(['1681', '1683', '5780']),
      institutions: new Set([]),
      events: new Set([]),
    },
  ],
  [
    '6879',
    {
      kind: 'institution',
      id: '6879',
      label: 'Hotel Bellevue, Vienna',
      persons: new Set(['6882']),
      places: new Set(['6881']),
      institutions: new Set([]),
      events: new Set([]),
    },
  ],
  [
    '6950',
    {
      kind: 'institution',
      id: '6950',
      label: 'Henndorfer Kreis (Henndorf Circle)',
      persons: new Set(['6960', '6958', '6959', '6953', '6951']),
      places: new Set(['6952']),
      institutions: new Set([]),
      events: new Set([]),
    },
  ],
  [
    '1480',
    {
      kind: 'institution',
      id: '1480',
      label: 'B. W. Huebsch',
      persons: new Set(['1481', '1482']),
      places: new Set([]),
      institutions: new Set([]),
      events: new Set([]),
    },
  ],
  [
    '1483',
    {
      kind: 'institution',
      id: '1483',
      label: 'The Freeman',
      persons: new Set(['1484', '1485', '1486']),
      places: new Set([]),
      institutions: new Set([]),
      events: new Set([]),
    },
  ],
  [
    '1487',
    {
      kind: 'institution',
      id: '1487',
      label: 'Viking Press',
      persons: new Set(['1488', '1489', '1490', '1493']),
      places: new Set(['7171']),
      institutions: new Set([]),
      events: new Set([]),
    },
  ],
  [
    '548',
    {
      kind: 'institution',
      id: '548',
      label: 'Philadelphia Public Ledger',
      persons: new Set(['550']),
      places: new Set([]),
      institutions: new Set([]),
      events: new Set([]),
    },
  ],
  [
    '551',
    {
      kind: 'institution',
      id: '551',
      label: 'European office of the Philadelphia Public Ledger',
      persons: new Set(['553']),
      places: new Set([]),
      institutions: new Set([]),
      events: new Set([]),
    },
  ],
  [
    '569',
    {
      kind: 'institution',
      id: '569',
      label: 'The New York Evening Post',
      persons: new Set(['570']),
      places: new Set([]),
      institutions: new Set([]),
      events: new Set([]),
    },
  ],
  [
    '906',
    {
      kind: 'institution',
      id: '906',
      label: 'New York Herald Tribune',
      persons: new Set(['907', '7121', '2133']),
      places: new Set([]),
      institutions: new Set([]),
      events: new Set([]),
    },
  ],
  [
    '1953',
    {
      kind: 'institution',
      id: '1953',
      label: 'Café Louvre',
      persons: new Set([
        '1958',
        '1957',
        '1956',
        '1959',
        '5636',
        '5638',
        '6392',
        '6792',
        '6364',
        '5637',
      ]),
      places: new Set(['1954']),
      institutions: new Set([]),
      events: new Set([]),
    },
  ],
  [
    '2787',
    {
      kind: 'institution',
      id: '2787',
      label: 'National American Woman Suffrage Association',
      persons: new Set(['2790']),
      places: new Set(['2789']),
      institutions: new Set([]),
      events: new Set([]),
    },
  ],
  [
    '5624',
    {
      kind: 'institution',
      id: '5624',
      label: 'New York Post',
      persons: new Set(['5625']),
      places: new Set([]),
      institutions: new Set([]),
      events: new Set([]),
    },
  ],
  [
    '5626',
    {
      kind: 'institution',
      id: '5626',
      label: 'Lewis Institute (Chicago, IL)',
      persons: new Set(['5627']),
      places: new Set(['7830']),
      institutions: new Set([]),
      events: new Set([]),
    },
  ],
  [
    '2866',
    {
      kind: 'institution',
      id: '2866',
      label: 'Syracuse University, New York',
      persons: new Set(['5630']),
      places: new Set([]),
      institutions: new Set([]),
      events: new Set([]),
    },
  ],
  [
    '1648',
    {
      kind: 'institution',
      id: '1648',
      label: 'Story',
      persons: new Set(['5930', '1649', '1650']),
      places: new Set(['5927', '5942']),
      institutions: new Set([]),
      events: new Set([]),
    },
  ],
  [
    '6001',
    {
      kind: 'institution',
      id: '6001',
      label: 'Central Telegraph Office Vienna',
      persons: new Set(['6322', '6900', '6321', '6323', '6903', '6902']),
      places: new Set(['6003']),
      institutions: new Set([]),
      events: new Set([]),
    },
  ],
  [
    '5168',
    {
      kind: 'institution',
      id: '5168',
      label: 'the Stammtisch of foreign correspondents at the Café Louvre',
      persons: new Set(['6781', '5169', '6782', '6784', '6785', '6780']),
      places: new Set([]),
      institutions: new Set([]),
      events: new Set([]),
    },
  ],
  [
    '1099',
    {
      kind: 'institution',
      id: '1099',
      label: 'Kaiserlich-Königliches Deutsches Staats-Realgymnasium Prag',
      persons: new Set(['1103']),
      places: new Set(['1100', '1102']),
      institutions: new Set([]),
      events: new Set([]),
    },
  ],
  [
    '1135',
    {
      kind: 'institution',
      id: '1135',
      label: 'Kurt Wolff Verlag',
      persons: new Set(['1134']),
      places: new Set(['1136', '1137']),
      institutions: new Set([]),
      events: new Set([]),
    },
  ],
  [
    '7166',
    {
      kind: 'institution',
      id: '7166',
      label: 'Imperial Palace Hotel, Santa Magherita Ligure',
      persons: new Set(['7169']),
      places: new Set(['7168']),
      institutions: new Set([]),
      events: new Set([]),
    },
  ],
  [
    '971',
    {
      kind: 'institution',
      id: '971',
      label: 'Czechoslovakian citizenship',
      persons: new Set(['972']),
      places: new Set([]),
      institutions: new Set([]),
      events: new Set([]),
    },
  ],
  [
    '977',
    {
      kind: 'institution',
      id: '977',
      label: 'Prager Tagblatt',
      persons: new Set(['978']),
      places: new Set([]),
      institutions: new Set([]),
      events: new Set([]),
    },
  ],
  [
    '979',
    {
      kind: 'institution',
      id: '979',
      label: 'Redaktion Leipziger Tageblatt',
      persons: new Set(['981']),
      places: new Set(['980']),
      institutions: new Set([]),
      events: new Set([]),
    },
  ],
  [
    '985',
    {
      kind: 'institution',
      id: '985',
      label: 'Selbstwehr (Wochenzeitschrift, Prag)',
      persons: new Set(['986']),
      places: new Set([]),
      institutions: new Set([]),
      events: new Set([]),
    },
  ],
  [
    '987',
    {
      kind: 'institution',
      id: '987',
      label: 'Universität Prag',
      persons: new Set(['989']),
      places: new Set(['988']),
      institutions: new Set([]),
      events: new Set([]),
    },
  ],
  [
    '998',
    {
      kind: 'institution',
      id: '998',
      label: 'Deutsches Realgymnasium in Prag-Smíchov',
      persons: new Set(['999']),
      places: new Set([]),
      institutions: new Set([]),
      events: new Set([]),
    },
  ],
  [
    '1010',
    {
      kind: 'institution',
      id: '1010',
      label: 'Wiener Zeitung GmbH',
      persons: new Set(['1012']),
      places: new Set(['1011']),
      institutions: new Set([]),
      events: new Set([]),
    },
  ],
  [
    '1013',
    {
      kind: 'institution',
      id: '1013',
      label: 'Die Presse',
      persons: new Set(['1014']),
      places: new Set([]),
      institutions: new Set([]),
      events: new Set([]),
    },
  ],
  [
    '664',
    {
      kind: 'institution',
      id: '664',
      label: 'Rot-Weiß-Rot',
      persons: new Set(['1015', '666']),
      places: new Set(['824']),
      institutions: new Set([]),
      events: new Set([]),
    },
  ],
  [
    '828',
    {
      kind: 'institution',
      id: '828',
      label: 'FORVM: Österreichische Monatsblätter für kulturelle Freiheit',
      persons: new Set(['1016', '7307']),
      places: new Set([]),
      institutions: new Set([]),
      events: new Set([]),
    },
  ],
  [
    '1017',
    {
      kind: 'institution',
      id: '1017',
      label: 'Süddeutsche Zeitung GmbH',
      persons: new Set(['1020']),
      places: new Set(['1019']),
      institutions: new Set([]),
      events: new Set([]),
    },
  ],
  [
    '1036',
    {
      kind: 'institution',
      id: '1036',
      label: "Café de l'Europe",
      persons: new Set(['1038']),
      places: new Set(['1037', '1962']),
      institutions: new Set([]),
      events: new Set([]),
    },
  ],
  [
    '1035',
    {
      kind: 'institution',
      id: '1035',
      label: 'Café Rebhuhn',
      persons: new Set(['1040']),
      places: new Set(['1039', '1966']),
      institutions: new Set([]),
      events: new Set([]),
    },
  ],
  [
    '1046',
    {
      kind: 'institution',
      id: '1046',
      label: 'Grand Café Odeon',
      persons: new Set(['1048']),
      places: new Set(['1047']),
      institutions: new Set([]),
      events: new Set([]),
    },
  ],
  [
    '803',
    {
      kind: 'institution',
      id: '803',
      label: 'Film-, Theater-, und Musikabteilung der US-Botschaft in Wien',
      persons: new Set(['804']),
      places: new Set([]),
      institutions: new Set([]),
      events: new Set([]),
    },
  ],
  [
    '3151',
    {
      kind: 'institution',
      id: '3151',
      label: 'Schottengymnasium in Wien',
      persons: new Set(['6029', '3153']),
      places: new Set(['3152']),
      institutions: new Set([]),
      events: new Set([]),
    },
  ],
  [
    '1371',
    {
      kind: 'institution',
      id: '1371',
      label: 'Akademie für Musik und Darstellende Kunst (Vienna)',
      persons: new Set(['6030', '2729', '7275']),
      places: new Set([]),
      institutions: new Set([]),
      events: new Set([]),
    },
  ],
  [
    '7250',
    {
      kind: 'institution',
      id: '7250',
      label: 'Cosmopol-Film',
      persons: new Set(['7251']),
      places: new Set([]),
      institutions: new Set([]),
      events: new Set([]),
    },
  ],
  [
    '691',
    {
      kind: 'institution',
      id: '691',
      label: 'Neue Freie Presse, Redaktion',
      persons: new Set(['693', '6343']),
      places: new Set(['692']),
      institutions: new Set([]),
      events: new Set([]),
    },
  ],
  [
    '696',
    {
      kind: 'institution',
      id: '696',
      label: 'Colorado College, Colorado Springs',
      persons: new Set(['699']),
      places: new Set(['698', '8129']),
      institutions: new Set([]),
      events: new Set([]),
    },
  ],
  [
    '1192',
    {
      kind: 'institution',
      id: '1192',
      label: 'Austrian citizenship',
      persons: new Set(['2635', '2010', '1193']),
      places: new Set([]),
      institutions: new Set([]),
      events: new Set([]),
    },
  ],
  [
    '5415',
    {
      kind: 'institution',
      id: '5415',
      label: 'US Information Service Branch (ISB)',
      persons: new Set(['2639']),
      places: new Set([]),
      institutions: new Set([]),
      events: new Set([]),
    },
  ],
  [
    '2819',
    {
      kind: 'institution',
      id: '2819',
      label: 'Radio-Verkehrs-AG (RAVAG)',
      persons: new Set(['2820']),
      places: new Set([]),
      institutions: new Set([]),
      events: new Set([]),
    },
  ],
  [
    '759',
    {
      kind: 'institution',
      id: '759',
      label: 'Salzburg Festival',
      persons: new Set(['7533', '2017', '2343', '2342', '1712', '1832', '7149', '6061']),
      places: new Set(['7835']),
      institutions: new Set([]),
      events: new Set([]),
    },
  ],
  [
    '7580',
    {
      kind: 'institution',
      id: '7580',
      label: 'European Film Fund',
      persons: new Set(['7582', '7581', '7597']),
      places: new Set(['7590']),
      institutions: new Set([]),
      events: new Set([]),
    },
  ],
  [
    '7718',
    {
      kind: 'institution',
      id: '7718',
      label: 'Austrian Federal Ministry for Commerce and Transport',
      persons: new Set(['7719']),
      places: new Set([]),
      institutions: new Set([]),
      events: new Set([]),
    },
  ],
  [
    '2028',
    {
      kind: 'institution',
      id: '2028',
      label: 'Max Reinhardt Seminar',
      persons: new Set(['7983', '2029']),
      places: new Set(['7269']),
      institutions: new Set([]),
      events: new Set([]),
    },
  ],
  [
    '1422',
    {
      kind: 'institution',
      id: '1422',
      label: 'Schloss Leopoldskron',
      persons: new Set(['1910', '6947', '4964', '1714', '6949']),
      places: new Set(['1425', '1912']),
      institutions: new Set([]),
      events: new Set([]),
    },
  ],
  [
    '1211',
    {
      kind: 'institution',
      id: '1211',
      label: 'Deutsches Theater Berlin',
      persons: new Set(['7261', '7262', '7309', '1215']),
      places: new Set(['1213', '1214']),
      institutions: new Set([]),
      events: new Set([]),
    },
  ],
  [
    '7270',
    {
      kind: 'institution',
      id: '7270',
      label: 'Max Reinhardt Workshop of Stage, Screen and Radio',
      persons: new Set(['7272', '8082', '7273']),
      places: new Set(['7271']),
      institutions: new Set([]),
      events: new Set([]),
    },
  ],
  [
    '2534',
    {
      kind: 'institution',
      id: '2534',
      label: 'The Seven Arts',
      persons: new Set(['2535']),
      places: new Set([]),
      institutions: new Set([]),
      events: new Set([]),
    },
  ],
  [
    '2081',
    {
      kind: 'institution',
      id: '2081',
      label: 'Bundesgymnasium (Wien- Innere Stadt)',
      persons: new Set(['2084']),
      places: new Set(['2083']),
      institutions: new Set([]),
      events: new Set([]),
    },
  ],
  [
    '2093',
    {
      kind: 'institution',
      id: '2093',
      label: 'Universität Czernowitz',
      persons: new Set(['2095']),
      places: new Set(['2094']),
      institutions: new Set([]),
      events: new Set([]),
    },
  ],
  [
    '2097',
    {
      kind: 'institution',
      id: '2097',
      label: 'British Museum',
      persons: new Set(['2100', '2520']),
      places: new Set(['2499']),
      institutions: new Set([]),
      events: new Set([]),
    },
  ],
  [
    '1311',
    {
      kind: 'institution',
      id: '1311',
      label: 'Columbia University',
      persons: new Set(['1631', '6772', '8122', '2967']),
      places: new Set(['1312', '7824']),
      institutions: new Set([]),
      events: new Set([]),
    },
  ],
  [
    '1222',
    {
      kind: 'institution',
      id: '1222',
      label: 'New School for Social Research',
      persons: new Set(['2540', '2743', '7286', '1225']),
      places: new Set(['1224', '7159']),
      institutions: new Set([]),
      events: new Set([]),
    },
  ],
  [
    '6640',
    {
      kind: 'institution',
      id: '6640',
      label: 'Yaddo Foundation',
      persons: new Set(['6642', '6641']),
      places: new Set(['8156']),
      institutions: new Set([]),
      events: new Set([]),
    },
  ],
  [
    '718',
    {
      kind: 'institution',
      id: '718',
      label: 'Roman Catholic',
      persons: new Set(['1146', '1304']),
      places: new Set([]),
      institutions: new Set([]),
      events: new Set([]),
    },
  ],
  [
    '1609',
    {
      kind: 'institution',
      id: '1609',
      label: 'Pension Franz',
      persons: new Set(['6946', '1612', '1613', '6062']),
      places: new Set(['1610']),
      institutions: new Set([]),
      events: new Set([]),
    },
  ],
  [
    '8656',
    {
      kind: 'institution',
      id: '8656',
      label: 'German reeducation program',
      persons: new Set(['8660', '8661']),
      places: new Set([]),
      institutions: new Set([]),
      events: new Set([]),
    },
  ],
  [
    '707',
    {
      kind: 'institution',
      id: '707',
      label: 'University of Chicago',
      persons: new Set(['1705', '2363', '750', '709', '7917']),
      places: new Set(['708']),
      institutions: new Set([]),
      events: new Set([]),
    },
  ],
  [
    '1718',
    {
      kind: 'institution',
      id: '1718',
      label: 'Hotel Bristol, Vienna',
      persons: new Set(['1719', '8093']),
      places: new Set(['1720', '5829']),
      institutions: new Set([]),
      events: new Set([]),
    },
  ],
  [
    '1722',
    {
      kind: 'institution',
      id: '1722',
      label: 'Schloss Cobenzl',
      persons: new Set(['1725']),
      places: new Set(['1723', '1724', '5831']),
      institutions: new Set([]),
      events: new Set([]),
    },
  ],
  [
    '1899',
    {
      kind: 'institution',
      id: '1899',
      label: 'Oberlin College',
      persons: new Set(['1902']),
      places: new Set(['1901']),
      institutions: new Set([]),
      events: new Set([]),
    },
  ],
  [
    '2173',
    {
      kind: 'institution',
      id: '2173',
      label: 'American Academy in Rome',
      persons: new Set(['2176']),
      places: new Set(['2174']),
      institutions: new Set([]),
      events: new Set([]),
    },
  ],
  [
    '2354',
    {
      kind: 'institution',
      id: '2354',
      label: 'Pulitzer Prize',
      persons: new Set(['2356', '2364', '2383']),
      places: new Set([]),
      institutions: new Set([]),
      events: new Set([]),
    },
  ],
  [
    '2358',
    {
      kind: 'institution',
      id: '2358',
      label: 'Yale University',
      persons: new Set(['2360', '2812']),
      places: new Set(['2359']),
      institutions: new Set([]),
      events: new Set([]),
    },
  ],
  [
    '2366',
    {
      kind: 'institution',
      id: '2366',
      label: 'Princeton University',
      persons: new Set(['2369', '7498', '7503']),
      places: new Set(['2368']),
      institutions: new Set([]),
      events: new Set([]),
    },
  ],
  [
    '2370',
    {
      kind: 'institution',
      id: '2370',
      label: 'Lawrenceville School',
      persons: new Set(['2373']),
      places: new Set(['2372']),
      institutions: new Set([]),
      events: new Set([]),
    },
  ],
  [
    '5009',
    {
      kind: 'institution',
      id: '5009',
      label: 'United States Army, Air Forces',
      persons: new Set(['5010']),
      places: new Set([]),
      institutions: new Set([]),
      events: new Set([]),
    },
  ],
  [
    '6285',
    {
      kind: 'institution',
      id: '6285',
      label: 'Hotel Bayerischer Hof',
      persons: new Set(['6288']),
      places: new Set(['6287']),
      institutions: new Set([]),
      events: new Set([]),
    },
  ],
  [
    '1802',
    {
      kind: 'institution',
      id: '1802',
      label: 'E.P. Tal & Co Verlag',
      persons: new Set(['6290', '1803']),
      places: new Set(['5838']),
      institutions: new Set([]),
      events: new Set([]),
    },
  ],
  [
    '6650',
    {
      kind: 'institution',
      id: '6650',
      label: 'Albatross Books',
      persons: new Set(['6651']),
      places: new Set(['6652']),
      institutions: new Set([]),
      events: new Set([]),
    },
  ],
  [
    '1700',
    {
      kind: 'institution',
      id: '1700',
      label: 'Schloss Belvedere',
      persons: new Set(['1702']),
      places: new Set(['1701']),
      institutions: new Set([]),
      events: new Set([]),
    },
  ],
  [
    '2107',
    {
      kind: 'institution',
      id: '2107',
      label: 'Wiener Staatsoper',
      persons: new Set(['2109', '2110', '2257', '2264']),
      places: new Set(['8176']),
      institutions: new Set([]),
      events: new Set([]),
    },
  ],
  [
    '2111',
    {
      kind: 'institution',
      id: '2111',
      label: 'Stephansdom',
      persons: new Set(['2112']),
      places: new Set(['8173']),
      institutions: new Set([]),
      events: new Set([]),
    },
  ],
  [
    '2236',
    {
      kind: 'institution',
      id: '2236',
      label: 'Villa Kenwin',
      persons: new Set(['2238', '8372', '2239', '2240', '2241', '2243', '2269']),
      places: new Set(['2237', '5736']),
      institutions: new Set([]),
      events: new Set([]),
    },
  ],
  [
    '2277',
    {
      kind: 'institution',
      id: '2277',
      label: 'Michaelerkirche',
      persons: new Set(['2279']),
      places: new Set(['2278']),
      institutions: new Set([]),
      events: new Set([]),
    },
  ],
  [
    '2280',
    {
      kind: 'institution',
      id: '2280',
      label: 'Votiv Cinema',
      persons: new Set(['2282', '2283', '2284']),
      places: new Set(['2281', '8377']),
      institutions: new Set([]),
      events: new Set([]),
    },
  ],
  [
    '2497',
    {
      kind: 'institution',
      id: '2497',
      label: 'Bryn Mawr College, PA',
      persons: new Set(['2498']),
      places: new Set([]),
      institutions: new Set([]),
      events: new Set([]),
    },
  ],
  [
    '2501',
    {
      kind: 'institution',
      id: '2501',
      label: 'The Egoist',
      persons: new Set(['2502']),
      places: new Set([]),
      institutions: new Set([]),
      events: new Set([]),
    },
  ],
  [
    '2506',
    {
      kind: 'institution',
      id: '2506',
      label: 'The Comrade',
      persons: new Set(['2507']),
      places: new Set([]),
      institutions: new Set([]),
      events: new Set([]),
    },
  ],
  [
    '2516',
    {
      kind: 'institution',
      id: '2516',
      label: 'Poetry',
      persons: new Set(['2519', '2517']),
      places: new Set([]),
      institutions: new Set([]),
      events: new Set([]),
    },
  ],
  [
    '926',
    {
      kind: 'institution',
      id: '926',
      label: 'Mädchenlyzeum',
      persons: new Set(['927', '936', '933']),
      places: new Set(['928', '932']),
      institutions: new Set([]),
      events: new Set([]),
    },
  ],
  [
    '4297',
    {
      kind: 'institution',
      id: '4297',
      label: 'The Manchester Guardian (since 1959 The Guardian)',
      persons: new Set(['4300']),
      places: new Set([]),
      institutions: new Set([]),
      events: new Set([]),
    },
  ],
  [
    '1914',
    {
      kind: 'institution',
      id: '1914',
      label: 'The Nation',
      persons: new Set(['4301', '1915', '4274']),
      places: new Set([]),
      institutions: new Set([]),
      events: new Set([]),
    },
  ],
  [
    '4061',
    {
      kind: 'institution',
      id: '4061',
      label: 'The New Republic',
      persons: new Set(['4302', '6395']),
      places: new Set([]),
      institutions: new Set([]),
      events: new Set([]),
    },
  ],
  [
    '4298',
    {
      kind: 'institution',
      id: '4298',
      label: 'The American Mercury',
      persons: new Set(['4303', '4299']),
      places: new Set([]),
      institutions: new Set([]),
      events: new Set([]),
    },
  ],
  [
    '4305',
    {
      kind: 'institution',
      id: '4305',
      label: 'Die Neue Zeitung',
      persons: new Set(['4306']),
      places: new Set([]),
      institutions: new Set([]),
      events: new Set([]),
    },
  ],
  [
    '4309',
    {
      kind: 'institution',
      id: '4309',
      label: 'Voice of America',
      persons: new Set(['4310', '4311']),
      places: new Set([]),
      institutions: new Set([]),
      events: new Set([]),
    },
  ],
  [
    '5227',
    {
      kind: 'institution',
      id: '5227',
      label: 'Anglo-American Press Association',
      persons: new Set(['6372', '5228', '6406', '6373', '6398', '6407']),
      places: new Set([]),
      institutions: new Set([]),
      events: new Set([]),
    },
  ],
  [
    '6383',
    {
      kind: 'institution',
      id: '6383',
      label: 'Philadelphia Inquirer',
      persons: new Set(['6384']),
      places: new Set([]),
      institutions: new Set([]),
      events: new Set([]),
    },
  ],
  [
    '6385',
    {
      kind: 'institution',
      id: '6385',
      label: 'New York Daily News',
      persons: new Set(['6386']),
      places: new Set([]),
      institutions: new Set([]),
      events: new Set([]),
    },
  ],
  [
    '2557',
    {
      kind: 'institution',
      id: '2557',
      label: "Harper's Magazine",
      persons: new Set(['6387', '5922']),
      places: new Set([]),
      institutions: new Set([]),
      events: new Set([]),
    },
  ],
  [
    '6583',
    {
      kind: 'institution',
      id: '6583',
      label: '-',
      persons: new Set(['6584']),
      places: new Set([]),
      institutions: new Set([]),
      events: new Set([]),
    },
  ],
  [
    '560',
    {
      kind: 'institution',
      id: '560',
      label: 'Chicago Daily News',
      persons: new Set(['6585', '561']),
      places: new Set(['7832']),
      institutions: new Set([]),
      events: new Set([]),
    },
  ],
  [
    '6361',
    {
      kind: 'institution',
      id: '6361',
      label: 'Café Imperial',
      persons: new Set(['6363']),
      places: new Set(['6362']),
      institutions: new Set([]),
      events: new Set([]),
    },
  ],
  [
    '909',
    {
      kind: 'institution',
      id: '909',
      label: 'Vanity Fair (magazine)',
      persons: new Set(['6394', '910']),
      places: new Set([]),
      institutions: new Set([]),
      events: new Set([]),
    },
  ],
  [
    '6396',
    {
      kind: 'institution',
      id: '6396',
      label: 'The Atlantic',
      persons: new Set(['6397']),
      places: new Set([]),
      institutions: new Set([]),
      events: new Set([]),
    },
  ],
  [
    '6416',
    {
      kind: 'institution',
      id: '6416',
      label: 'Radio Austria AG',
      persons: new Set(['6419', '6420']),
      places: new Set(['6418']),
      institutions: new Set([]),
      events: new Set([]),
    },
  ],
  [
    '4412',
    {
      kind: 'institution',
      id: '4412',
      label: 'Arbeiterzeitung (Wien)',
      persons: new Set(['6673', '6669']),
      places: new Set([]),
      institutions: new Set([]),
      events: new Set([]),
    },
  ],
  [
    '6727',
    {
      kind: 'institution',
      id: '6727',
      label: 'Chicago Daily News, London office',
      persons: new Set(['6728']),
      places: new Set([]),
      institutions: new Set([]),
      events: new Set([]),
    },
  ],
  [
    '6324',
    {
      kind: 'institution',
      id: '6324',
      label: 'Rathauskeller Vienna',
      persons: new Set(['6885', '8008', '8009', '8012', '8011']),
      places: new Set(['6326']),
      institutions: new Set([]),
      events: new Set([]),
    },
  ],
  [
    '564',
    {
      kind: 'institution',
      id: '564',
      label: 'Chicago Tribune',
      persons: new Set(['710', '567', '6700', '2952']),
      places: new Set(['566']),
      institutions: new Set([]),
      events: new Set([]),
    },
  ],
  [
    '2994',
    {
      kind: 'institution',
      id: '2994',
      label: 'Coe College',
      persons: new Set(['2997']),
      places: new Set(['2996']),
      institutions: new Set([]),
      events: new Set([]),
    },
  ],
  [
    '5910',
    {
      kind: 'institution',
      id: '5910',
      label: 'Columbia Broadcasting System',
      persons: new Set(['5911']),
      places: new Set([]),
      institutions: new Set([]),
      events: new Set([]),
    },
  ],
  [
    '5912',
    {
      kind: 'institution',
      id: '5912',
      label: 'Berlin bureau of Hearst’s Universal News Service',
      persons: new Set(['5913']),
      places: new Set([]),
      institutions: new Set([]),
      events: new Set([]),
    },
  ],
  [
    '1468',
    {
      kind: 'institution',
      id: '1468',
      label: 'The New York Times',
      persons: new Set(['1469', '5673']),
      places: new Set([]),
      institutions: new Set([]),
      events: new Set([]),
    },
  ],
  [
    '1470',
    {
      kind: 'institution',
      id: '1470',
      label: 'Daily Telegraph',
      persons: new Set(['1471']),
      places: new Set([]),
      institutions: new Set([]),
      events: new Set([]),
    },
  ],
  [
    '6736',
    {
      kind: 'institution',
      id: '6736',
      label: 'United Press International',
      persons: new Set(['6737']),
      places: new Set([]),
      institutions: new Set([]),
      events: new Set([]),
    },
  ],
  [
    '3113',
    {
      kind: 'institution',
      id: '3113',
      label: 'Wofford College, Spartanburg, SC',
      persons: new Set(['6771']),
      places: new Set(['3115', '8121']),
      institutions: new Set([]),
      events: new Set([]),
    },
  ],
  [
    '6774',
    {
      kind: 'institution',
      id: '6774',
      label: 'Amepress',
      persons: new Set(['6775']),
      places: new Set([]),
      institutions: new Set([]),
      events: new Set([]),
    },
  ],
  [
    '5682',
    {
      kind: 'institution',
      id: '5682',
      label: 'Grand Hotel, Vienna',
      persons: new Set(['5683']),
      places: new Set(['5815']),
      institutions: new Set([]),
      events: new Set([]),
    },
  ],
  [
    '5690',
    {
      kind: 'institution',
      id: '5690',
      label: 'Hotel Ritz, Budapest',
      persons: new Set(['5691']),
      places: new Set(['5817']),
      institutions: new Set([]),
      events: new Set([]),
    },
  ],
  [
    '6161',
    {
      kind: 'institution',
      id: '6161',
      label: 'Grand Hotel Gardone Riviera, Lake Garda',
      persons: new Set(['6164']),
      places: new Set(['6163']),
      institutions: new Set([]),
      events: new Set([]),
    },
  ],
  [
    '5993',
    {
      kind: 'institution',
      id: '5993',
      label: 'Quaker',
      persons: new Set(['5994']),
      places: new Set([]),
      institutions: new Set([]),
      events: new Set([]),
    },
  ],
  [
    '5937',
    {
      kind: 'institution',
      id: '5937',
      label: 'New York Sun',
      persons: new Set(['5938']),
      places: new Set([]),
      institutions: new Set([]),
      events: new Set([]),
    },
  ],
  [
    '6671',
    {
      kind: 'institution',
      id: '6671',
      label: 'Embassy of the United States in Vienna',
      persons: new Set(['6672']),
      places: new Set([]),
      institutions: new Set([]),
      events: new Set([]),
    },
  ],
  [
    '5968',
    {
      kind: 'institution',
      id: '5968',
      label: 'League of Nations',
      persons: new Set(['5969']),
      places: new Set([]),
      institutions: new Set([]),
      events: new Set([]),
    },
  ],
  [
    '5972',
    {
      kind: 'institution',
      id: '5972',
      label: 'News Chronicle (London)',
      persons: new Set(['5973']),
      places: new Set([]),
      institutions: new Set([]),
      events: new Set([]),
    },
  ],
  [
    '6294',
    {
      kind: 'institution',
      id: '6294',
      label: 'Pennsylvania Academy of the Fine Arts',
      persons: new Set(['6296']),
      places: new Set(['6295']),
      institutions: new Set([]),
      events: new Set([]),
    },
  ],
  [
    '1420',
    {
      kind: 'institution',
      id: '1420',
      label: 'Hotel Imperial',
      persons: new Set(['6297']),
      places: new Set(['1421', '6299']),
      institutions: new Set([]),
      events: new Set([]),
    },
  ],
  [
    '6313',
    {
      kind: 'institution',
      id: '6313',
      label: 'Die praktische Berlinerin',
      persons: new Set(['6314']),
      places: new Set([]),
      institutions: new Set([]),
      events: new Set([]),
    },
  ],
  [
    '9733',
    {
      kind: 'institution',
      id: '9733',
      label: 'Austro-American Institute (AAI)',
      persons: new Set(['9742', '9750']),
      places: new Set([]),
      institutions: new Set([]),
      events: new Set([]),
    },
  ],
  [
    '8364',
    {
      kind: 'institution',
      id: '8364',
      label: 'Vienna Psycho-Analytical Society',
      persons: new Set(['8366', '8365', '8367']),
      places: new Set([]),
      institutions: new Set([]),
      events: new Set([]),
    },
  ],
  [
    '2414',
    {
      kind: 'institution',
      id: '2414',
      label: 'The Ohio State University',
      persons: new Set(['2417']),
      places: new Set(['2416']),
      institutions: new Set([]),
      events: new Set([]),
    },
  ],
  [
    '3181',
    {
      kind: 'institution',
      id: '3181',
      label: 'University of Wisconsin-Madison',
      persons: new Set(['6055']),
      places: new Set(['3182']),
      institutions: new Set([]),
      events: new Set([]),
    },
  ],
  [
    '6056',
    {
      kind: 'institution',
      id: '6056',
      label: 'Brandeis University',
      persons: new Set(['6059']),
      places: new Set(['6058']),
      institutions: new Set([]),
      events: new Set([]),
    },
  ],
  [
    '6802',
    {
      kind: 'institution',
      id: '6802',
      label: 'Die Fackel',
      persons: new Set(['6803', '6812']),
      places: new Set([]),
      institutions: new Set([]),
      events: new Set([]),
    },
  ],
  [
    '6807',
    {
      kind: 'institution',
      id: '6807',
      label: 'Franz-Josephs-Gymnasium',
      persons: new Set(['6808']),
      places: new Set(['6810']),
      institutions: new Set([]),
      events: new Set([]),
    },
  ],
  [
    '7311',
    {
      kind: 'institution',
      id: '7311',
      label: 'Die Truppe',
      persons: new Set(['7629', '7312', '7627']),
      places: new Set(['7628']),
      institutions: new Set([]),
      events: new Set([]),
    },
  ],
  [
    '1173',
    {
      kind: 'institution',
      id: '1173',
      label: 'Verlag Die Fackel (Wien)',
      persons: new Set(['1175']),
      places: new Set(['1174']),
      institutions: new Set([]),
      events: new Set([]),
    },
  ],
  [
    '1176',
    {
      kind: 'institution',
      id: '1176',
      label: 'Schauspielhaus Dresden',
      persons: new Set(['1179']),
      places: new Set(['1178']),
      institutions: new Set([]),
      events: new Set([]),
    },
  ],
  [
    '6456',
    {
      kind: 'institution',
      id: '6456',
      label: 'Kunst, Literatur und Musik',
      persons: new Set(['6458']),
      places: new Set([]),
      institutions: new Set([]),
      events: new Set([]),
    },
  ],
  [
    '6459',
    {
      kind: 'institution',
      id: '6459',
      label: 'Books Abroad',
      persons: new Set(['6460']),
      places: new Set([]),
      institutions: new Set([]),
      events: new Set([]),
    },
  ],
  [
    '7308',
    {
      kind: 'institution',
      id: '7308',
      label: 'Freie Volksbühne Wien',
      persons: new Set(['7310']),
      places: new Set([]),
      institutions: new Set([]),
      events: new Set([]),
    },
  ],
  [
    '7313',
    {
      kind: 'institution',
      id: '7313',
      label: 'Düsseldorfer Schauspielhaus',
      persons: new Set(['7315']),
      places: new Set(['7314']),
      institutions: new Set([]),
      events: new Set([]),
    },
  ],
  [
    '7301',
    {
      kind: 'institution',
      id: '7301',
      label: 'Twentieth Century Fox Film Corporation, Hollywood',
      persons: new Set(['7316', '7303']),
      places: new Set(['7302']),
      institutions: new Set([]),
      events: new Set([]),
    },
  ],
  [
    '7322',
    {
      kind: 'institution',
      id: '7322',
      label: 'Akademietheater Wien',
      persons: new Set(['7324']),
      places: new Set(['7323']),
      institutions: new Set([]),
      events: new Set([]),
    },
  ],
  [
    '7325',
    {
      kind: 'institution',
      id: '7325',
      label: 'Gaumont British Picture Corporation (London)',
      persons: new Set(['7327']),
      places: new Set(['7326']),
      institutions: new Set([]),
      events: new Set([]),
    },
  ],
  [
    '7667',
    {
      kind: 'institution',
      id: '7667',
      label: 'Café Central (Wien)',
      persons: new Set(['7669']),
      places: new Set(['7668']),
      institutions: new Set([]),
      events: new Set([]),
    },
  ],
  [
    '7672',
    {
      kind: 'institution',
      id: '7672',
      label: 'Aurora Verlag',
      persons: new Set(['7673']),
      places: new Set([]),
      institutions: new Set([]),
      events: new Set([]),
    },
  ],
  [
    '7681',
    {
      kind: 'institution',
      id: '7681',
      label: 'Volksschule Zieglergasse',
      persons: new Set(['7682']),
      places: new Set(['7683']),
      institutions: new Set([]),
      events: new Set([]),
    },
  ],
  [
    '7684',
    {
      kind: 'institution',
      id: '7684',
      label: 'Amerlinggymnasium',
      persons: new Set(['7687']),
      places: new Set(['7686']),
      institutions: new Set([]),
      events: new Set([]),
    },
  ],
  [
    '915',
    {
      kind: 'institution',
      id: '915',
      label: 'Deutsches Schauspielhaus in Hamburg',
      persons: new Set(['918']),
      places: new Set(['917']),
      institutions: new Set([]),
      events: new Set([]),
    },
  ],
  [
    '7609',
    {
      kind: 'institution',
      id: '7609',
      label: 'Hollywood Anti-Nazi-League',
      persons: new Set(['7614']),
      places: new Set([]),
      institutions: new Set([]),
      events: new Set([]),
    },
  ],
  [
    '7615',
    {
      kind: 'institution',
      id: '7615',
      label: 'Screen Writers Guild',
      persons: new Set(['7616']),
      places: new Set([]),
      institutions: new Set([]),
      events: new Set([]),
    },
  ],
  [
    '7622',
    {
      kind: 'institution',
      id: '7622',
      label: 'Pressburger Stadttheater',
      persons: new Set(['7623']),
      places: new Set([]),
      institutions: new Set([]),
      events: new Set([]),
    },
  ],
  [
    '7335',
    {
      kind: 'institution',
      id: '7335',
      label: 'Neue Wiener Bühne',
      persons: new Set(['7624']),
      places: new Set(['7336']),
      institutions: new Set([]),
      events: new Set([]),
    },
  ],
  [
    '2722',
    {
      kind: 'institution',
      id: '2722',
      label: 'Warner Brothers Pictures',
      persons: new Set(['7632', '2730', '2724']),
      places: new Set(['7700']),
      institutions: new Set([]),
      events: new Set([]),
    },
  ],
  [
    '7635',
    {
      kind: 'institution',
      id: '7635',
      label: 'Metro-Goldwyn-Mayer (MGM)',
      persons: new Set(['7634']),
      places: new Set([]),
      institutions: new Set([]),
      events: new Set([]),
    },
  ],
  [
    '7637',
    {
      kind: 'institution',
      id: '7637',
      label: 'Hanns Eisler Defense Committee',
      persons: new Set(['7638', '7641']),
      places: new Set([]),
      institutions: new Set([]),
      events: new Set([]),
    },
  ],
  [
    '7223',
    {
      kind: 'institution',
      id: '7223',
      label: 'Akademie der Künste',
      persons: new Set(['7225']),
      places: new Set(['7224']),
      institutions: new Set([]),
      events: new Set([]),
    },
  ],
  [
    '7226',
    {
      kind: 'institution',
      id: '7226',
      label: 'Staatliches Konservatorium',
      persons: new Set(['7228']),
      places: new Set(['7227']),
      institutions: new Set([]),
      events: new Set([]),
    },
  ],
  [
    '7024',
    {
      kind: 'institution',
      id: '7024',
      label: 'University of California Los Angeles',
      persons: new Set(['7026']),
      places: new Set(['7025']),
      institutions: new Set([]),
      events: new Set([]),
    },
  ],
  [
    '7411',
    {
      kind: 'institution',
      id: '7411',
      label: 'Radio Research Project (Princeton University)',
      persons: new Set(['7414', '7422']),
      places: new Set([]),
      institutions: new Set([]),
      events: new Set([]),
    },
  ],
  [
    '9360',
    {
      kind: 'institution',
      id: '9360',
      label: 'Darmstädter Ferienkurse (Darmstadt Summer Course)',
      persons: new Set(['9370']),
      places: new Set([]),
      institutions: new Set([]),
      events: new Set([]),
    },
  ],
  [
    '4107',
    {
      kind: 'institution',
      id: '4107',
      label: 'Stanford Center for the Advanced Study of the Behavioral Sciences',
      persons: new Set(['4111']),
      places: new Set([]),
      institutions: new Set([]),
      events: new Set([]),
    },
  ],
  [
    '6433',
    {
      kind: 'institution',
      id: '6433',
      label: 'Faculty of Political Science of Columbia University',
      persons: new Set(['6434']),
      places: new Set([]),
      institutions: new Set([]),
      events: new Set([]),
    },
  ],
  [
    '7401',
    {
      kind: 'institution',
      id: '7401',
      label: 'Bureau of Applied Social Research',
      persons: new Set(['7403']),
      places: new Set([]),
      institutions: new Set([]),
      events: new Set([]),
    },
  ],
  [
    '7437',
    {
      kind: 'institution',
      id: '7437',
      label: 'Research Center, University of Newark',
      persons: new Set(['7438', '7446']),
      places: new Set([]),
      institutions: new Set([]),
      events: new Set([]),
    },
  ],
  [
    '7204',
    {
      kind: 'institution',
      id: '7204',
      label: 'Rockefeller Foundation',
      persons: new Set(['7439', '7489']),
      places: new Set(['7828']),
      institutions: new Set([]),
      events: new Set([]),
    },
  ],
  [
    '3221',
    {
      kind: 'institution',
      id: '3221',
      label: 'Université Paris-Sorbonne',
      persons: new Set(['7482', '7516']),
      places: new Set([]),
      institutions: new Set([]),
      events: new Set([]),
    },
  ],
  [
    '7485',
    {
      kind: 'institution',
      id: '7485',
      label: "Maison des sciences de l'homme",
      persons: new Set(['7487']),
      places: new Set([]),
      institutions: new Set([]),
      events: new Set([]),
    },
  ],
  [
    '7508',
    {
      kind: 'institution',
      id: '7508',
      label: 'Institut für Höhere Studien - Institute for Advanced Studies (IHS)',
      persons: new Set(['7510', '7509']),
      places: new Set(['7513']),
      institutions: new Set([]),
      events: new Set([]),
    },
  ],
  [
    '7972',
    {
      kind: 'institution',
      id: '7972',
      label: 'Insitute of Psychology, University of Vienna',
      persons: new Set(['7974']),
      places: new Set(['7973']),
      institutions: new Set([]),
      events: new Set([]),
    },
  ],
  [
    '7975',
    {
      kind: 'institution',
      id: '7975',
      label: 'American Sociological Association',
      persons: new Set(['7976']),
      places: new Set([]),
      institutions: new Set([]),
      events: new Set([]),
    },
  ],
  [
    '7505',
    {
      kind: 'institution',
      id: '7505',
      label: 'Wiener Konjunkturforschungsinstitut',
      persons: new Set(['7506']),
      places: new Set([]),
      institutions: new Set([]),
      events: new Set([]),
    },
  ],
  [
    '4444',
    {
      kind: 'institution',
      id: '4444',
      label: 'New York University',
      persons: new Set(['7511', '5889']),
      places: new Set([]),
      institutions: new Set([]),
      events: new Set([]),
    },
  ],
  [
    '7287',
    {
      kind: 'institution',
      id: '7287',
      label: 'University of Southern California',
      persons: new Set(['7289']),
      places: new Set(['7288']),
      institutions: new Set([]),
      events: new Set([]),
    },
  ],
  [
    '2731',
    {
      kind: 'institution',
      id: '2731',
      label: 'Paramount Pictures Corporation',
      persons: new Set(['7300', '2732']),
      places: new Set([]),
      institutions: new Set([]),
      events: new Set([]),
    },
  ],
  [
    '2720',
    {
      kind: 'institution',
      id: '2720',
      label: 'RKO Pictures, Hollywood',
      persons: new Set(['7304', '2721']),
      places: new Set(['7534']),
      institutions: new Set([]),
      events: new Set([]),
    },
  ],
  [
    '3808',
    {
      kind: 'institution',
      id: '3808',
      label: 'Clark University (Worcester, Mass.)',
      persons: new Set(['8358', '8360']),
      places: new Set(['3810']),
      institutions: new Set([]),
      events: new Set([]),
    },
  ],
  [
    '5826',
    {
      kind: 'institution',
      id: '5826',
      label: 'Research Group on the Study of Blind Children at the Hampstead Clinic',
      persons: new Set(['5827']),
      places: new Set([]),
      institutions: new Set([]),
      events: new Set([]),
    },
  ],
  [
    '8373',
    {
      kind: 'institution',
      id: '8373',
      label: 'Close Up',
      persons: new Set(['8374']),
      places: new Set([]),
      institutions: new Set([]),
      events: new Set([]),
    },
  ],
  [
    '7358',
    {
      kind: 'institution',
      id: '7358',
      label: 'Institut für Anatomie (Wien)',
      persons: new Set(['7360']),
      places: new Set(['7359']),
      institutions: new Set([]),
      events: new Set([]),
    },
  ],
  [
    '5192',
    {
      kind: 'institution',
      id: '5192',
      label: 'Catholicism',
      persons: new Set(['5193']),
      places: new Set([]),
      institutions: new Set([]),
      events: new Set([]),
    },
  ],
  [
    '5196',
    {
      kind: 'institution',
      id: '5196',
      label: 'Cambridge University',
      persons: new Set(['5197']),
      places: new Set([]),
      institutions: new Set([]),
      events: new Set([]),
    },
  ],
  [
    '5198',
    {
      kind: 'institution',
      id: '5198',
      label: 'Johns Hopkins University',
      persons: new Set(['5199']),
      places: new Set(['7721']),
      institutions: new Set([]),
      events: new Set([]),
    },
  ],
  [
    '5200',
    {
      kind: 'institution',
      id: '5200',
      label: 'Catholic University in Washington, D.C.',
      persons: new Set(['5201']),
      places: new Set(['7840']),
      institutions: new Set([]),
      events: new Set([]),
    },
  ],
  [
    '5204',
    {
      kind: 'institution',
      id: '5204',
      label: 'Austrian Academy of Sciences',
      persons: new Set(['5205']),
      places: new Set([]),
      institutions: new Set([]),
      events: new Set([]),
    },
  ],
  [
    '6846',
    {
      kind: 'institution',
      id: '6846',
      label: 'Kaiser-Wilhelm-Institut für Chemie',
      persons: new Set(['6848']),
      places: new Set(['6847']),
      institutions: new Set([]),
      events: new Set([]),
    },
  ],
  [
    '5860',
    {
      kind: 'institution',
      id: '5860',
      label: 'Kunstgewerbe Schule, Vienna',
      persons: new Set(['5861']),
      places: new Set([]),
      institutions: new Set([]),
      events: new Set([]),
    },
  ],
  [
    '2541',
    {
      kind: 'institution',
      id: '2541',
      label: 'American Medical Association (AMA) of Vienna',
      persons: new Set(['5856', '6543', '9698']),
      places: new Set(['2542', '7035', '9689']),
      institutions: new Set([]),
      events: new Set([]),
    },
  ],
  [
    '1205',
    {
      kind: 'institution',
      id: '1205',
      label: 'Theater Kiel',
      persons: new Set(['1208']),
      places: new Set(['1207']),
      institutions: new Set([]),
      events: new Set([]),
    },
  ],
  [
    '1227',
    {
      kind: 'institution',
      id: '1227',
      label: 'USA. Office of Strategic Services',
      persons: new Set(['1228']),
      places: new Set([]),
      institutions: new Set([]),
      events: new Set([]),
    },
  ],
  [
    '2711',
    {
      kind: 'institution',
      id: '2711',
      label: 'Ronacher Vienna',
      persons: new Set(['2713']),
      places: new Set(['2712']),
      institutions: new Set([]),
      events: new Set([]),
    },
  ],
  [
    '2727',
    {
      kind: 'institution',
      id: '2727',
      label: 'Selznick International Orchestra',
      persons: new Set(['2728']),
      places: new Set([]),
      institutions: new Set([]),
      events: new Set([]),
    },
  ],
  [
    '7695',
    {
      kind: 'institution',
      id: '7695',
      label: 'Ziegfeld Follies',
      persons: new Set(['7698']),
      places: new Set([]),
      institutions: new Set([]),
      events: new Set([]),
    },
  ],
  [
    '5656',
    {
      kind: 'institution',
      id: '5656',
      label: 'Der österreichische Volkswirt (Wien)',
      persons: new Set(['5657', '5660']),
      places: new Set([]),
      institutions: new Set([]),
      events: new Set([]),
    },
  ],
  [
    '5674',
    {
      kind: 'institution',
      id: '5674',
      label: 'Foreign Affairs',
      persons: new Set(['5675']),
      places: new Set([]),
      institutions: new Set([]),
      events: new Set([]),
    },
  ],
  [
    '167',
    {
      kind: 'institution',
      id: '167',
      label: 'Harvard University',
      persons: new Set(['169', '5071', '5888', '7918', '6173']),
      places: new Set(['168']),
      institutions: new Set([]),
      events: new Set([]),
    },
  ],
  [
    '3818',
    {
      kind: 'institution',
      id: '3818',
      label: 'University of Michigan',
      persons: new Set(['5068']),
      places: new Set(['3820']),
      institutions: new Set([]),
      events: new Set([]),
    },
  ],
  [
    '5078',
    {
      kind: 'institution',
      id: '5078',
      label: 'Smith College',
      persons: new Set(['5081']),
      places: new Set(['5080']),
      institutions: new Set([]),
      events: new Set([]),
    },
  ],
  [
    '5141',
    {
      kind: 'institution',
      id: '5141',
      label: 'Uniwersytet Warszawski',
      persons: new Set(['5144']),
      places: new Set(['5143']),
      institutions: new Set([]),
      events: new Set([]),
    },
  ],
  [
    '2915',
    {
      kind: 'institution',
      id: '2915',
      label: 'Socialist Party of America',
      persons: new Set(['2917']),
      places: new Set([]),
      institutions: new Set([]),
      events: new Set([]),
    },
  ],
  [
    '2916',
    {
      kind: 'institution',
      id: '2916',
      label: 'Communist Party USA',
      persons: new Set(['2918']),
      places: new Set([]),
      institutions: new Set([]),
      events: new Set([]),
    },
  ],
  [
    '2926',
    {
      kind: 'institution',
      id: '2926',
      label: 'New Masses',
      persons: new Set(['2927', '8002']),
      places: new Set([]),
      institutions: new Set([]),
      events: new Set([]),
    },
  ],
  [
    '2928',
    {
      kind: 'institution',
      id: '2928',
      label: 'The Partisan Review',
      persons: new Set(['2929']),
      places: new Set([]),
      institutions: new Set([]),
      events: new Set([]),
    },
  ],
  [
    '2956',
    {
      kind: 'institution',
      id: '2956',
      label: 'American Civil Liberties Union',
      persons: new Set(['2957']),
      places: new Set([]),
      institutions: new Set([]),
      events: new Set([]),
    },
  ],
  [
    '2968',
    {
      kind: 'institution',
      id: '2968',
      label: 'TASS Office New York',
      persons: new Set(['2969']),
      places: new Set([]),
      institutions: new Set([]),
      events: new Set([]),
    },
  ],
  [
    '2552',
    {
      kind: 'institution',
      id: '2552',
      label: 'Broom',
      persons: new Set(['2580', '6203']),
      places: new Set(['7418']),
      institutions: new Set([]),
      events: new Set([]),
    },
  ],
  [
    '2596',
    {
      kind: 'institution',
      id: '2596',
      label: 'The New Yorker',
      persons: new Set(['2597']),
      places: new Set([]),
      institutions: new Set([]),
      events: new Set([]),
    },
  ],
  [
    '2610',
    {
      kind: 'institution',
      id: '2610',
      label: 'Hotel Hellenstainer',
      persons: new Set(['2612']),
      places: new Set(['2611', '5870']),
      institutions: new Set([]),
      events: new Set([]),
    },
  ],
  [
    '5864',
    {
      kind: 'institution',
      id: '5864',
      label: 'Hotel Kaiserhof',
      persons: new Set(['5866']),
      places: new Set(['5865', '5868']),
      institutions: new Set([]),
      events: new Set([]),
    },
  ],
  [
    '1511',
    {
      kind: 'institution',
      id: '1511',
      label: 'Foreign Students Club',
      persons: new Set(['1513', '5943']),
      places: new Set(['1512']),
      institutions: new Set([]),
      events: new Set([]),
    },
  ],
  [
    '2661',
    {
      kind: 'institution',
      id: '2661',
      label: 'Pomona College, California',
      persons: new Set(['2662']),
      places: new Set([]),
      institutions: new Set([]),
      events: new Set([]),
    },
  ],
  [
    '6924',
    {
      kind: 'institution',
      id: '6924',
      label: 'University of Nebraska - Lincoln',
      persons: new Set(['6927']),
      places: new Set(['6926']),
      institutions: new Set([]),
      events: new Set([]),
    },
  ],
  [
    '1505',
    {
      kind: 'institution',
      id: '1505',
      label: 'Vereinte Nationen. Relief and Rehabilitation Administration',
      persons: new Set(['1506']),
      places: new Set([]),
      institutions: new Set([]),
      events: new Set([]),
    },
  ],
  [
    '5881',
    {
      kind: 'institution',
      id: '5881',
      label: 'Palais Windisch-Graetz',
      persons: new Set(['5884']),
      places: new Set(['5882']),
      institutions: new Set([]),
      events: new Set([]),
    },
  ],
  [
    '3085',
    {
      kind: 'institution',
      id: '3085',
      label: 'Naturhistorisches Museum Wien',
      persons: new Set(['3087', '3146', '3885']),
      places: new Set(['3086', '5809']),
      institutions: new Set([]),
      events: new Set([]),
    },
  ],
  [
    '3913',
    {
      kind: 'institution',
      id: '3913',
      label: 'Österreichische Akademie der Wissenschaften',
      persons: new Set(['3915']),
      places: new Set(['3914']),
      institutions: new Set([]),
      events: new Set([]),
    },
  ],
  [
    '3934',
    {
      kind: 'institution',
      id: '3934',
      label: 'Museum of Comparative Zoology',
      persons: new Set(['3948']),
      places: new Set([]),
      institutions: new Set([]),
      events: new Set([]),
    },
  ],
  [
    '6535',
    {
      kind: 'institution',
      id: '6535',
      label: 'British Columbia Medical Association',
      persons: new Set(['6536']),
      places: new Set([]),
      institutions: new Set([]),
      events: new Set([]),
    },
  ],
  [
    '6537',
    {
      kind: 'institution',
      id: '6537',
      label: 'Canadian Medical Association',
      persons: new Set(['6538']),
      places: new Set([]),
      institutions: new Set([]),
      events: new Set([]),
    },
  ],
  [
    '3835',
    {
      kind: 'institution',
      id: '3835',
      label: 'University of North Carolina',
      persons: new Set(['5887']),
      places: new Set([]),
      institutions: new Set([]),
      events: new Set([]),
    },
  ],
  [
    '6261',
    {
      kind: 'institution',
      id: '6261',
      label: 'Hotel Höller',
      persons: new Set(['6263']),
      places: new Set(['6262']),
      institutions: new Set([]),
      events: new Set([]),
    },
  ],
  [
    '1286',
    {
      kind: 'institution',
      id: '1286',
      label: 'Kunsthistorisches Museum Wien',
      persons: new Set(['6278']),
      places: new Set(['1287']),
      institutions: new Set([]),
      events: new Set([]),
    },
  ],
  [
    '1378',
    {
      kind: 'institution',
      id: '1378',
      label: 'Kabarett Simpl',
      persons: new Set(['6279']),
      places: new Set(['1379']),
      institutions: new Set([]),
      events: new Set([]),
    },
  ],
  [
    '5327',
    {
      kind: 'institution',
      id: '5327',
      label: 'Amerikanische Kinderhilfsaktion',
      persons: new Set(['5333']),
      places: new Set(['5331']),
      institutions: new Set([]),
      events: new Set([]),
    },
  ],
  [
    '5334',
    {
      kind: 'institution',
      id: '5334',
      label: "Pediatric Clinic of Vienna's General Hospital",
      persons: new Set(['5335']),
      places: new Set([]),
      institutions: new Set([]),
      events: new Set([]),
    },
  ],
  [
    '3104',
    {
      kind: 'institution',
      id: '3104',
      label: 'Johns Hopkins University',
      persons: new Set(['5336']),
      places: new Set([]),
      institutions: new Set([]),
      events: new Set([]),
    },
  ],
  [
    '9701',
    {
      kind: 'institution',
      id: '9701',
      label: "Infants' programme (League of Nations)",
      persons: new Set(['9700']),
      places: new Set([]),
      institutions: new Set([]),
      events: new Set([]),
    },
  ],
  [
    '6842',
    {
      kind: 'institution',
      id: '6842',
      label: 'University of Canterbury, NZ',
      persons: new Set(['6843']),
      places: new Set(['6845']),
      institutions: new Set([]),
      events: new Set([]),
    },
  ],
  [
    '1263',
    {
      kind: 'institution',
      id: '1263',
      label: "St. John's University Shanghai",
      persons: new Set(['1264']),
      places: new Set(['7930']),
      institutions: new Set([]),
      events: new Set([]),
    },
  ],
  [
    '1265',
    {
      kind: 'institution',
      id: '1265',
      label: 'University of California Berkeley',
      persons: new Set(['1268', '7906', '8136', '8137']),
      places: new Set(['1267', '7745']),
      institutions: new Set([]),
      events: new Set([]),
    },
  ],
  [
    '2773',
    {
      kind: 'institution',
      id: '2773',
      label: 'Institut Wiener Kreis',
      persons: new Set(['2774', '7928']),
      places: new Set([]),
      institutions: new Set([]),
      events: new Set([]),
    },
  ],
  [
    '7913',
    {
      kind: 'institution',
      id: '7913',
      label: 'Millersville University of Pennsylvania',
      persons: new Set(['5214', '7916']),
      places: new Set(['7747', '7915']),
      institutions: new Set([]),
      events: new Set([]),
    },
  ],
  [
    '7750',
    {
      kind: 'institution',
      id: '7750',
      label: 'University of California, Davis',
      persons: new Set(['7751']),
      places: new Set(['7932']),
      institutions: new Set([]),
      events: new Set([]),
    },
  ],
  [
    '1274',
    {
      kind: 'institution',
      id: '1274',
      label: 'Café Hummel',
      persons: new Set(['7905']),
      places: new Set(['1276']),
      institutions: new Set([]),
      events: new Set([]),
    },
  ],
  [
    '7907',
    {
      kind: 'institution',
      id: '7907',
      label: 'Mills College',
      persons: new Set(['7910']),
      places: new Set(['7909', '7934']),
      institutions: new Set([]),
      events: new Set([]),
    },
  ],
  [
    '7911',
    {
      kind: 'institution',
      id: '7911',
      label: 'City University of New York',
      persons: new Set(['7912']),
      places: new Set(['7935']),
      institutions: new Set([]),
      events: new Set([]),
    },
  ],
  [
    '7922',
    {
      kind: 'institution',
      id: '7922',
      label: 'Universität Kassel',
      persons: new Set(['7927']),
      places: new Set(['7924', '7926']),
      institutions: new Set([]),
      events: new Set([]),
    },
  ],
  [
    '7936',
    {
      kind: 'institution',
      id: '7936',
      label: 'Fulbright Program',
      persons: new Set(['7937']),
      places: new Set([]),
      institutions: new Set([]),
      events: new Set([]),
    },
  ],
  [
    '8132',
    {
      kind: 'institution',
      id: '8132',
      label: 'Gymnasium Albertgasse',
      persons: new Set(['8135']),
      places: new Set(['8134']),
      institutions: new Set([]),
      events: new Set([]),
    },
  ],
  [
    '7384',
    {
      kind: 'institution',
      id: '7384',
      label: 'Auslandsvertretung der österreichischen Sozialisten (AVOES)',
      persons: new Set(['7385']),
      places: new Set([]),
      institutions: new Set([]),
      events: new Set([]),
    },
  ],
  [
    '7392',
    {
      kind: 'institution',
      id: '7392',
      label: 'Revolutionary Socialists',
      persons: new Set(['7393']),
      places: new Set([]),
      institutions: new Set([]),
      events: new Set([]),
    },
  ],
  [
    '7398',
    {
      kind: 'institution',
      id: '7398',
      label: 'International Rescue Committee (IRC)',
      persons: new Set(['7399']),
      places: new Set([]),
      institutions: new Set([]),
      events: new Set([]),
    },
  ],
  [
    '7646',
    {
      kind: 'institution',
      id: '7646',
      label: 'Österreichische Kinderfreunde (St. Veit a. d. Glan)',
      persons: new Set(['7650']),
      places: new Set(['7649']),
      institutions: new Set([]),
      events: new Set([]),
    },
  ],
  [
    '7653',
    {
      kind: 'institution',
      id: '7653',
      label: 'SDAP (St. Veit a. d. Glan)',
      persons: new Set(['7652']),
      places: new Set([]),
      institutions: new Set([]),
      events: new Set([]),
    },
  ],
  [
    '7660',
    {
      kind: 'institution',
      id: '7660',
      label: 'American Friends of Vietnam',
      persons: new Set(['7661']),
      places: new Set([]),
      institutions: new Set([]),
      events: new Set([]),
    },
  ],
  [
    '6174',
    {
      kind: 'institution',
      id: '6174',
      label: 'Harvard Advocate',
      persons: new Set(['6175']),
      places: new Set([]),
      institutions: new Set([]),
      events: new Set([]),
    },
  ],
  [
    '6179',
    {
      kind: 'institution',
      id: '6179',
      label: 'American Field Service',
      persons: new Set(['6180']),
      places: new Set([]),
      institutions: new Set([]),
      events: new Set([]),
    },
  ],
  [
    '2550',
    {
      kind: 'institution',
      id: '2550',
      label: 'Secession',
      persons: new Set(['6200']),
      places: new Set([]),
      institutions: new Set([]),
      events: new Set([]),
    },
  ],
])
