export const institutions = new Map([
  [
    '765',
    {
      kind: 'institution',
      id: '765',
      label: 'University of Vienna',
      persons: new Set([
        '622',
        '646',
        '223',
        '414',
        '445',
        '462',
        '3083',
        '487',
        '616',
        '7378',
        '413',
        '540',
        '3427',
        '7404',
        '280',
        '649',
        '640',
        '604',
      ]),
      places: new Set([]),
      institutions: new Set([]),
    },
  ],
  [
    '982',
    {
      kind: 'institution',
      id: '982',
      label: 'American citizenship',
      persons: new Set([
        '622',
        '2841',
        '382',
        '520',
        '426',
        '676',
        '608',
        '624',
        '672',
        '506',
        '507',
        '633',
        '616',
        '389',
        '401',
        '610',
        '471',
        '7404',
        '280',
        '604',
      ]),
      places: new Set([]),
      institutions: new Set([]),
    },
  ],
  [
    '2839',
    {
      kind: 'institution',
      id: '2839',
      label: 'Junge Wien',
      persons: new Set(['622']),
      places: new Set([]),
      institutions: new Set([]),
    },
  ],
  [
    '1145',
    {
      kind: 'institution',
      id: '1145',
      label: 'Jewish',
      persons: new Set(['622', '1', '414', '676', '413', '540', '640']),
      places: new Set([]),
      institutions: new Set([]),
    },
  ],
  [
    '592',
    {
      kind: 'institution',
      id: '592',
      label: 'Theater in der Josefstadt',
      persons: new Set(['622', '676', '493', '616', '610']),
      places: new Set([]),
      institutions: new Set([]),
    },
  ],
  [
    '716',
    {
      kind: 'institution',
      id: '716',
      label: 'Burgtheater Wien',
      persons: new Set(['622', '463', '507', '616', '610', '604']),
      places: new Set([]),
      institutions: new Set([]),
    },
  ],
  [
    '5551',
    {
      kind: 'institution',
      id: '5551',
      label: 'Pension "Jägerhof"',
      persons: new Set(['622']),
      places: new Set([]),
      institutions: new Set([]),
    },
  ],
  [
    '167',
    {
      kind: 'institution',
      id: '167',
      label: 'Harvard University',
      persons: new Set(['1', '507', '649', '355']),
      places: new Set([]),
      institutions: new Set([]),
    },
  ],
  [
    '3818',
    {
      kind: 'institution',
      id: '3818',
      label: 'University of Michigan',
      persons: new Set(['1']),
      places: new Set([]),
      institutions: new Set([]),
    },
  ],
  [
    '5078',
    {
      kind: 'institution',
      id: '5078',
      label: 'Smith College',
      persons: new Set(['1']),
      places: new Set([]),
      institutions: new Set([]),
    },
  ],
  [
    '5141',
    {
      kind: 'institution',
      id: '5141',
      label: 'Uniwersytet Warszawski',
      persons: new Set(['1']),
      places: new Set([]),
      institutions: new Set([]),
    },
  ],
  [
    '2107',
    {
      kind: 'institution',
      id: '2107',
      label: 'Wiener Staatsoper',
      persons: new Set(['358', '1530', '504']),
      places: new Set([]),
      institutions: new Set([]),
    },
  ],
  [
    '691',
    {
      kind: 'institution',
      id: '691',
      label: 'Neue Freie Presse, Redaktion',
      persons: new Set(['1623', '616']),
      places: new Set([]),
      institutions: new Set([]),
    },
  ],
  [
    '6324',
    {
      kind: 'institution',
      id: '6324',
      label: 'Rathauskeller Vienna',
      persons: new Set(['1623', '520', '504', '6334', '6328', '466']),
      places: new Set([]),
      institutions: new Set([]),
    },
  ],
  [
    '2552',
    {
      kind: 'institution',
      id: '2552',
      label: 'Broom',
      persons: new Set(['382', '355']),
      places: new Set([]),
      institutions: new Set([]),
    },
  ],
  [
    '2596',
    {
      kind: 'institution',
      id: '2596',
      label: 'New Yorker',
      persons: new Set(['382']),
      places: new Set([]),
      institutions: new Set([]),
    },
  ],
  [
    '2610',
    {
      kind: 'institution',
      id: '2610',
      label: 'Hotel Hellenstainer',
      persons: new Set(['382']),
      places: new Set([]),
      institutions: new Set([]),
    },
  ],
  [
    '5864',
    {
      kind: 'institution',
      id: '5864',
      label: 'Hotel Kaiserhof',
      persons: new Set(['382']),
      places: new Set([]),
      institutions: new Set([]),
    },
  ],
  [
    '5826',
    {
      kind: 'institution',
      id: '5826',
      label: 'Research Group on the Study of Blind Children at the Hampstead Clinic',
      persons: new Set(['344']),
      places: new Set([]),
      institutions: new Set([]),
    },
  ],
  [
    '1648',
    {
      kind: 'institution',
      id: '1648',
      label: 'Story',
      persons: new Set(['346', '546', '388']),
      places: new Set([]),
      institutions: new Set([]),
    },
  ],
  [
    '5937',
    {
      kind: 'institution',
      id: '5937',
      label: 'New York Sun',
      persons: new Set(['346']),
      places: new Set([]),
      institutions: new Set([]),
    },
  ],
  [
    '1953',
    {
      kind: 'institution',
      id: '1953',
      label: 'Café Louvre',
      persons: new Set(['346', '520', '425', '523', '483', '546', '6561', '387', '392', '448']),
      places: new Set([]),
      institutions: new Set([]),
    },
  ],
  [
    '5227',
    {
      kind: 'institution',
      id: '5227',
      label: 'Anglo-American Press Association',
      persons: new Set(['346', '520', '523', '387', '388', '392']),
      places: new Set([]),
      institutions: new Set([]),
    },
  ],
  [
    '1680',
    {
      kind: 'institution',
      id: '1680',
      label: 'Hotel Regina',
      persons: new Set(['1530', '509']),
      places: new Set([]),
      institutions: new Set([]),
    },
  ],
  [
    '1700',
    {
      kind: 'institution',
      id: '1700',
      label: 'Schloss Belvedere',
      persons: new Set(['1530']),
      places: new Set([]),
      institutions: new Set([]),
    },
  ],
  [
    '2111',
    {
      kind: 'institution',
      id: '2111',
      label: 'Stephansdom',
      persons: new Set(['1530']),
      places: new Set([]),
      institutions: new Set([]),
    },
  ],
  [
    '2236',
    {
      kind: 'institution',
      id: '2236',
      label: 'Villa Kenwin',
      persons: new Set(['1530', '1881', '433', '445']),
      places: new Set([]),
      institutions: new Set([]),
    },
  ],
  [
    '2277',
    {
      kind: 'institution',
      id: '2277',
      label: 'Michaelerkirche',
      persons: new Set(['1530']),
      places: new Set([]),
      institutions: new Set([]),
    },
  ],
  [
    '2280',
    {
      kind: 'institution',
      id: '2280',
      label: 'Votiv Cinema',
      persons: new Set(['1530', '1881', '445']),
      places: new Set([]),
      institutions: new Set([]),
    },
  ],
  [
    '2497',
    {
      kind: 'institution',
      id: '2497',
      label: 'Bryn Mawr College',
      persons: new Set(['1530']),
      places: new Set([]),
      institutions: new Set([]),
    },
  ],
  [
    '2501',
    {
      kind: 'institution',
      id: '2501',
      label: 'The Egoist',
      persons: new Set(['1530']),
      places: new Set([]),
      institutions: new Set([]),
    },
  ],
  [
    '2506',
    {
      kind: 'institution',
      id: '2506',
      label: 'The Comrade',
      persons: new Set(['1530']),
      places: new Set([]),
      institutions: new Set([]),
    },
  ],
  [
    '2516',
    {
      kind: 'institution',
      id: '2516',
      label: 'Poetry',
      persons: new Set(['1530', '105']),
      places: new Set([]),
      institutions: new Set([]),
    },
  ],
  [
    '2097',
    {
      kind: 'institution',
      id: '2097',
      label: 'British Museum',
      persons: new Set(['1530', '414']),
      places: new Set([]),
      institutions: new Set([]),
    },
  ],
  [
    '5192',
    {
      kind: 'institution',
      id: '5192',
      label: 'Catholicism',
      persons: new Set(['646']),
      places: new Set([]),
      institutions: new Set([]),
    },
  ],
  [
    '5196',
    {
      kind: 'institution',
      id: '5196',
      label: 'Cambridge University',
      persons: new Set(['646']),
      places: new Set([]),
      institutions: new Set([]),
    },
  ],
  [
    '5198',
    {
      kind: 'institution',
      id: '5198',
      label: 'Johns Hopkins University',
      persons: new Set(['646']),
      places: new Set([]),
      institutions: new Set([]),
    },
  ],
  [
    '5200',
    {
      kind: 'institution',
      id: '5200',
      label: 'Catholic University in Washington, D.C.',
      persons: new Set(['646']),
      places: new Set([]),
      institutions: new Set([]),
    },
  ],
  [
    '5204',
    {
      kind: 'institution',
      id: '5204',
      label: 'Austrian Academy of Sciences',
      persons: new Set(['646']),
      places: new Set([]),
      institutions: new Set([]),
    },
  ],
  [
    '560',
    {
      kind: 'institution',
      id: '560',
      label: 'Chicago Daily News',
      persons: new Set(['520', '387']),
      places: new Set([]),
      institutions: new Set([]),
    },
  ],
  [
    '707',
    {
      kind: 'institution',
      id: '707',
      label: 'University of Chicago',
      persons: new Set(['520', '477', '672', '649']),
      places: new Set([]),
      institutions: new Set([]),
    },
  ],
  [
    '1914',
    {
      kind: 'institution',
      id: '1914',
      label: 'The Nation',
      persons: new Set(['520', '426', '387']),
      places: new Set([]),
      institutions: new Set([]),
    },
  ],
  [
    '2557',
    {
      kind: 'institution',
      id: '2557',
      label: "Harper's Magazine",
      persons: new Set(['520', '387']),
      places: new Set([]),
      institutions: new Set([]),
    },
  ],
  [
    '6001',
    {
      kind: 'institution',
      id: '6001',
      label: 'Central Telegraph Office Vienna',
      persons: new Set(['520', '523', '546', '6561', '387', '392']),
      places: new Set([]),
      institutions: new Set([]),
    },
  ],
  [
    '6361',
    {
      kind: 'institution',
      id: '6361',
      label: 'Café Imperial',
      persons: new Set(['520']),
      places: new Set([]),
      institutions: new Set([]),
    },
  ],
  [
    '909',
    {
      kind: 'institution',
      id: '909',
      label: 'Vanity Fair (magazine)',
      persons: new Set(['520', '443']),
      places: new Set([]),
      institutions: new Set([]),
    },
  ],
  [
    '4061',
    {
      kind: 'institution',
      id: '4061',
      label: 'The New Republic',
      persons: new Set(['520', '387']),
      places: new Set([]),
      institutions: new Set([]),
    },
  ],
  [
    '6396',
    {
      kind: 'institution',
      id: '6396',
      label: 'The Atlantic',
      persons: new Set(['520']),
      places: new Set([]),
      institutions: new Set([]),
    },
  ],
  [
    '6416',
    {
      kind: 'institution',
      id: '6416',
      label: 'Radio Austria AG',
      persons: new Set(['520', '523']),
      places: new Set([]),
      institutions: new Set([]),
    },
  ],
  [
    '4412',
    {
      kind: 'institution',
      id: '4412',
      label: 'Arbeiterzeitung (Wien)',
      persons: new Set(['520', '1930']),
      places: new Set([]),
      institutions: new Set([]),
    },
  ],
  [
    '6727',
    {
      kind: 'institution',
      id: '6727',
      label: 'Chicago Daily News, London office',
      persons: new Set(['520']),
      places: new Set([]),
      institutions: new Set([]),
    },
  ],
  [
    '5168',
    {
      kind: 'institution',
      id: '5168',
      label: 'the Stammtisch of foreign correspondents at the Café Louvre',
      persons: new Set(['520', '523', '546', '6561', '387', '392']),
      places: new Set([]),
      institutions: new Set([]),
    },
  ],
  [
    '1802',
    {
      kind: 'institution',
      id: '1802',
      label: 'E.P. Tal & Co Verlag',
      persons: new Set(['577', '1801']),
      places: new Set([]),
      institutions: new Set([]),
    },
  ],
  [
    '6650',
    {
      kind: 'institution',
      id: '6650',
      label: 'Albatross Books',
      persons: new Set(['577']),
      places: new Set([]),
      institutions: new Set([]),
    },
  ],
  [
    '1033',
    {
      kind: 'institution',
      id: '1033',
      label: 'Café Herrenhof',
      persons: new Set(['403', '608', '624', '401', '413', '640']),
      places: new Set([]),
      institutions: new Set([]),
    },
  ],
  [
    '2081',
    {
      kind: 'institution',
      id: '2081',
      label: 'Bundesgymnasium (Wien- Innere Stadt)',
      persons: new Set(['414']),
      places: new Set([]),
      institutions: new Set([]),
    },
  ],
  [
    '2093',
    {
      kind: 'institution',
      id: '2093',
      label: 'Universität Czernowitz',
      persons: new Set(['414']),
      places: new Set([]),
      institutions: new Set([]),
    },
  ],
  [
    '926',
    {
      kind: 'institution',
      id: '926',
      label: 'Mädchenlyzeum',
      persons: new Set(['416', '474', '471']),
      places: new Set([]),
      institutions: new Set([]),
    },
  ],
  [
    '1609',
    {
      kind: 'institution',
      id: '1609',
      label: 'Pension Franz',
      persons: new Set(['426', '470', '1605', '81']),
      places: new Set([]),
      institutions: new Set([]),
    },
  ],
  [
    '2414',
    {
      kind: 'institution',
      id: '2414',
      label: 'The Ohio State University',
      persons: new Set(['426']),
      places: new Set([]),
      institutions: new Set([]),
    },
  ],
  [
    '3181',
    {
      kind: 'institution',
      id: '3181',
      label: 'University of Wisconsin-Madison',
      persons: new Set(['426']),
      places: new Set([]),
      institutions: new Set([]),
    },
  ],
  [
    '6056',
    {
      kind: 'institution',
      id: '6056',
      label: 'Brandeis University',
      persons: new Set(['426']),
      places: new Set([]),
      institutions: new Set([]),
    },
  ],
  [
    '5682',
    {
      kind: 'institution',
      id: '5682',
      label: 'Grand Hotel, Vienna',
      persons: new Set(['443']),
      places: new Set([]),
      institutions: new Set([]),
    },
  ],
  [
    '5690',
    {
      kind: 'institution',
      id: '5690',
      label: 'Hotel Ritz, Budapest',
      persons: new Set(['443']),
      places: new Set([]),
      institutions: new Set([]),
    },
  ],
  [
    '1511',
    {
      kind: 'institution',
      id: '1511',
      label: 'Foreign Students Club',
      persons: new Set(['447', '487']),
      places: new Set([]),
      institutions: new Set([]),
    },
  ],
  [
    '2661',
    {
      kind: 'institution',
      id: '2661',
      label: 'Pomona College, California',
      persons: new Set(['447']),
      places: new Set([]),
      institutions: new Set([]),
    },
  ],
  [
    '6924',
    {
      kind: 'institution',
      id: '6924',
      label: 'University of Nebraska - Lincoln',
      persons: new Set(['447']),
      places: new Set([]),
      institutions: new Set([]),
    },
  ],
  [
    '1422',
    {
      kind: 'institution',
      id: '1422',
      label: 'Schloss Leopoldskron',
      persons: new Set(['676', '477', '493', '672', '81']),
      places: new Set([]),
      institutions: new Set([]),
    },
  ],
  [
    '1192',
    {
      kind: 'institution',
      id: '1192',
      label: 'Austrian citizenship',
      persons: new Set(['676', '616', '604']),
      places: new Set([]),
      institutions: new Set([]),
    },
  ],
  [
    '759',
    {
      kind: 'institution',
      id: '759',
      label: 'Salzburg Festival',
      persons: new Set(['676', '477', '492', '493', '672', '616', '105']),
      places: new Set([]),
      institutions: new Set([]),
    },
  ],
  [
    '2028',
    {
      kind: 'institution',
      id: '2028',
      label: 'Max Reinhardt Seminar',
      persons: new Set(['676', '616']),
      places: new Set([]),
      institutions: new Set([]),
    },
  ],
  [
    '6950',
    {
      kind: 'institution',
      id: '6950',
      label: 'Henndorfer Kreis (Henndorf Circle)',
      persons: new Set(['676', '624', '633', '509', '81']),
      places: new Set([]),
      institutions: new Set([]),
    },
  ],
  [
    '1211',
    {
      kind: 'institution',
      id: '1211',
      label: 'Deutsches Theater Berlin',
      persons: new Set(['676', '633', '604']),
      places: new Set([]),
      institutions: new Set([]),
    },
  ],
  [
    '7270',
    {
      kind: 'institution',
      id: '7270',
      label: 'Max Reinhardt Workshop of Stage, Screen and Radio',
      persons: new Set(['676', '672', '2699']),
      places: new Set([]),
      institutions: new Set([]),
    },
  ],
  [
    '5860',
    {
      kind: 'institution',
      id: '5860',
      label: 'Kunstgewerbe Schule, Vienna',
      persons: new Set(['5850']),
      places: new Set([]),
      institutions: new Set([]),
    },
  ],
  [
    '2541',
    {
      kind: 'institution',
      id: '2541',
      label: 'American Medical Association of Vienna',
      persons: new Set(['5854', '504', '6533']),
      places: new Set([]),
      institutions: new Set([]),
    },
  ],
  [
    '564',
    {
      kind: 'institution',
      id: '564',
      label: 'Chicago Tribune',
      persons: new Set(['477', '523', '389', '476']),
      places: new Set([]),
      institutions: new Set([]),
    },
  ],
  [
    '906',
    {
      kind: 'institution',
      id: '906',
      label: 'New York Herald Tribune',
      persons: new Set(['477', '523', '546']),
      places: new Set([]),
      institutions: new Set([]),
    },
  ],
  [
    '2994',
    {
      kind: 'institution',
      id: '2994',
      label: 'Coe College',
      persons: new Set(['523']),
      places: new Set([]),
      institutions: new Set([]),
    },
  ],
  [
    '5910',
    {
      kind: 'institution',
      id: '5910',
      label: 'Columbia Broadcasting System',
      persons: new Set(['523']),
      places: new Set([]),
      institutions: new Set([]),
    },
  ],
  [
    '5912',
    {
      kind: 'institution',
      id: '5912',
      label: 'Berlin bureau of Hearst’s Universal News Service',
      persons: new Set(['523']),
      places: new Set([]),
      institutions: new Set([]),
    },
  ],
  [
    '3085',
    {
      kind: 'institution',
      id: '3085',
      label: 'Naturhistorisches Museum Wien',
      persons: new Set(['3083']),
      places: new Set([]),
      institutions: new Set([]),
    },
  ],
  [
    '3151',
    {
      kind: 'institution',
      id: '3151',
      label: 'Schottengymnasium in Wien',
      persons: new Set(['3083', '610']),
      places: new Set([]),
      institutions: new Set([]),
    },
  ],
  [
    '3913',
    {
      kind: 'institution',
      id: '3913',
      label: 'Österreichische Akademie der Wissenschaften',
      persons: new Set(['3083']),
      places: new Set([]),
      institutions: new Set([]),
    },
  ],
  [
    '3934',
    {
      kind: 'institution',
      id: '3934',
      label: 'Museum of Comparative Zoology',
      persons: new Set(['3083']),
      places: new Set([]),
      institutions: new Set([]),
    },
  ],
  [
    '5656',
    {
      kind: 'institution',
      id: '5656',
      label: 'Der österreichische Volkswirt (Wien)',
      persons: new Set(['484', '5658']),
      places: new Set([]),
      institutions: new Set([]),
    },
  ],
  [
    '1468',
    {
      kind: 'institution',
      id: '1468',
      label: 'The New York Times',
      persons: new Set(['484', '392']),
      places: new Set([]),
      institutions: new Set([]),
    },
  ],
  [
    '5674',
    {
      kind: 'institution',
      id: '5674',
      label: 'Foreign Affairs',
      persons: new Set(['484']),
      places: new Set([]),
      institutions: new Set([]),
    },
  ],
  [
    '1505',
    {
      kind: 'institution',
      id: '1505',
      label: 'Vereinte Nationen. Relief and Rehabilitation Administration',
      persons: new Set(['487']),
      places: new Set([]),
      institutions: new Set([]),
    },
  ],
  [
    '5881',
    {
      kind: 'institution',
      id: '5881',
      label: 'Palais Windisch-Graetz',
      persons: new Set(['487']),
      places: new Set([]),
      institutions: new Set([]),
    },
  ],
  [
    '971',
    {
      kind: 'institution',
      id: '971',
      label: 'Czechoslovakian citizenship',
      persons: new Set(['608']),
      places: new Set([]),
      institutions: new Set([]),
    },
  ],
  [
    '977',
    {
      kind: 'institution',
      id: '977',
      label: 'Prager Tagblatt',
      persons: new Set(['608']),
      places: new Set([]),
      institutions: new Set([]),
    },
  ],
  [
    '979',
    {
      kind: 'institution',
      id: '979',
      label: 'Redaktion Leipziger Tageblatt',
      persons: new Set(['608']),
      places: new Set([]),
      institutions: new Set([]),
    },
  ],
  [
    '985',
    {
      kind: 'institution',
      id: '985',
      label: 'Selbstwehr (Wochenzeitschrift, Prag)',
      persons: new Set(['608']),
      places: new Set([]),
      institutions: new Set([]),
    },
  ],
  [
    '987',
    {
      kind: 'institution',
      id: '987',
      label: 'Universität Prag',
      persons: new Set(['608']),
      places: new Set([]),
      institutions: new Set([]),
    },
  ],
  [
    '998',
    {
      kind: 'institution',
      id: '998',
      label: 'Deutsches Realgymnasium in Prag-Smíchov',
      persons: new Set(['608']),
      places: new Set([]),
      institutions: new Set([]),
    },
  ],
  [
    '1010',
    {
      kind: 'institution',
      id: '1010',
      label: 'Wiener Zeitung GmbH',
      persons: new Set(['608']),
      places: new Set([]),
      institutions: new Set([]),
    },
  ],
  [
    '1013',
    {
      kind: 'institution',
      id: '1013',
      label: 'Die Presse',
      persons: new Set(['608']),
      places: new Set([]),
      institutions: new Set([]),
    },
  ],
  [
    '664',
    {
      kind: 'institution',
      id: '664',
      label: 'Rot-Weiß-Rot',
      persons: new Set(['608', '5377', '610']),
      places: new Set([]),
      institutions: new Set([]),
    },
  ],
  [
    '828',
    {
      kind: 'institution',
      id: '828',
      label: 'FORVM: Österreichische Monatsblätter für kulturelle Freiheit',
      persons: new Set(['608']),
      places: new Set([]),
      institutions: new Set([]),
    },
  ],
  [
    '1017',
    {
      kind: 'institution',
      id: '1017',
      label: 'Süddeutsche Zeitung GmbH',
      persons: new Set(['608']),
      places: new Set([]),
      institutions: new Set([]),
    },
  ],
  [
    '1036',
    {
      kind: 'institution',
      id: '1036',
      label: "Café de l'Europe",
      persons: new Set(['608']),
      places: new Set([]),
      institutions: new Set([]),
    },
  ],
  [
    '1035',
    {
      kind: 'institution',
      id: '1035',
      label: 'Café Rebhuhn',
      persons: new Set(['608']),
      places: new Set([]),
      institutions: new Set([]),
    },
  ],
  [
    '1046',
    {
      kind: 'institution',
      id: '1046',
      label: 'Grand Café Odeon',
      persons: new Set(['608']),
      places: new Set([]),
      institutions: new Set([]),
    },
  ],
  [
    '548',
    {
      kind: 'institution',
      id: '548',
      label: 'Philadelphia Public Ledger',
      persons: new Set(['546']),
      places: new Set([]),
      institutions: new Set([]),
    },
  ],
  [
    '551',
    {
      kind: 'institution',
      id: '551',
      label: 'European office of the Philadelphia Public Ledger',
      persons: new Set(['546']),
      places: new Set([]),
      institutions: new Set([]),
    },
  ],
  [
    '569',
    {
      kind: 'institution',
      id: '569',
      label: 'The New York Evening Post',
      persons: new Set(['546']),
      places: new Set([]),
      institutions: new Set([]),
    },
  ],
  [
    '2787',
    {
      kind: 'institution',
      id: '2787',
      label: 'National American Woman Suffrage Association',
      persons: new Set(['546']),
      places: new Set([]),
      institutions: new Set([]),
    },
  ],
  [
    '5624',
    {
      kind: 'institution',
      id: '5624',
      label: 'New York Post',
      persons: new Set(['546']),
      places: new Set([]),
      institutions: new Set([]),
    },
  ],
  [
    '5626',
    {
      kind: 'institution',
      id: '5626',
      label: 'Lewis Institute (Chicago, IL)',
      persons: new Set(['546']),
      places: new Set([]),
      institutions: new Set([]),
    },
  ],
  [
    '2866',
    {
      kind: 'institution',
      id: '2866',
      label: 'Syracuse University, New York',
      persons: new Set(['546']),
      places: new Set([]),
      institutions: new Set([]),
    },
  ],
  [
    '1311',
    {
      kind: 'institution',
      id: '1311',
      label: 'Columbia University',
      persons: new Set(['492', '389', '6561']),
      places: new Set([]),
      institutions: new Set([]),
    },
  ],
  [
    '1222',
    {
      kind: 'institution',
      id: '1222',
      label: 'New School for Social Research',
      persons: new Set(['492', '633', '2707', '2703']),
      places: new Set([]),
      institutions: new Set([]),
    },
  ],
  [
    '6640',
    {
      kind: 'institution',
      id: '6640',
      label: 'Yaddo Foundation',
      persons: new Set(['492', '640']),
      places: new Set([]),
      institutions: new Set([]),
    },
  ],
  [
    '1483',
    {
      kind: 'institution',
      id: '1483',
      label: 'The Freeman',
      persons: new Set(['493', '406', '81']),
      places: new Set([]),
      institutions: new Set([]),
    },
  ],
  [
    '2534',
    {
      kind: 'institution',
      id: '2534',
      label: 'The Seven Arts',
      persons: new Set(['493']),
      places: new Set([]),
      institutions: new Set([]),
    },
  ],
  [
    '915',
    {
      kind: 'institution',
      id: '915',
      label: 'Deutsches Schauspielhaus in Hamburg',
      persons: new Set(['834']),
      places: new Set([]),
      institutions: new Set([]),
    },
  ],
  [
    '7609',
    {
      kind: 'institution',
      id: '7609',
      label: 'Hollywood Anti-Nazi-League',
      persons: new Set(['834']),
      places: new Set([]),
      institutions: new Set([]),
    },
  ],
  [
    '7615',
    {
      kind: 'institution',
      id: '7615',
      label: 'Screen Writers Guild',
      persons: new Set(['834']),
      places: new Set([]),
      institutions: new Set([]),
    },
  ],
  [
    '7622',
    {
      kind: 'institution',
      id: '7622',
      label: 'Pressburger Stadttheater',
      persons: new Set(['834']),
      places: new Set([]),
      institutions: new Set([]),
    },
  ],
  [
    '7335',
    {
      kind: 'institution',
      id: '7335',
      label: 'Neue Wiener Bühne',
      persons: new Set(['834']),
      places: new Set([]),
      institutions: new Set([]),
    },
  ],
  [
    '7311',
    {
      kind: 'institution',
      id: '7311',
      label: 'Die Truppe',
      persons: new Set(['834', '540', '604']),
      places: new Set([]),
      institutions: new Set([]),
    },
  ],
  [
    '2722',
    {
      kind: 'institution',
      id: '2722',
      label: 'Warner Brothers Pictures',
      persons: new Set(['834', '2699', '2689']),
      places: new Set([]),
      institutions: new Set([]),
    },
  ],
  [
    '7635',
    {
      kind: 'institution',
      id: '7635',
      label: 'Metro-Goldwyn-Mayer (MGM)',
      persons: new Set(['834']),
      places: new Set([]),
      institutions: new Set([]),
    },
  ],
  [
    '7637',
    {
      kind: 'institution',
      id: '7637',
      label: 'Hanns Eisler Defense Committee',
      persons: new Set(['834', '2707']),
      places: new Set([]),
      institutions: new Set([]),
    },
  ],
  [
    '5993',
    {
      kind: 'institution',
      id: '5993',
      label: 'Quaker',
      persons: new Set(['496']),
      places: new Set([]),
      institutions: new Set([]),
    },
  ],
  [
    '4309',
    {
      kind: 'institution',
      id: '4309',
      label: 'Voice of America',
      persons: new Set(['5377', '387']),
      places: new Set([]),
      institutions: new Set([]),
    },
  ],
  [
    '5295',
    {
      kind: 'institution',
      id: '5295',
      label: 'ABC  cabaret',
      persons: new Set(['5377']),
      places: new Set([]),
      institutions: new Set([]),
    },
  ],
  [
    '5311',
    {
      kind: 'institution',
      id: '5311',
      label: 'Die Arche',
      persons: new Set(['5377']),
      places: new Set([]),
      institutions: new Set([]),
    },
  ],
  [
    '5314',
    {
      kind: 'institution',
      id: '5314',
      label: 'Vienna Café',
      persons: new Set(['5377']),
      places: new Set([]),
      institutions: new Set([]),
    },
  ],
  [
    '5317',
    {
      kind: 'institution',
      id: '5317',
      label:
        'Österreichische Mediathek (Austrian audiovisual archive of the Technical Museum, Vienna)',
      persons: new Set(['5377']),
      places: new Set([]),
      institutions: new Set([]),
    },
  ],
  [
    '1099',
    {
      kind: 'institution',
      id: '1099',
      label: 'Kaiserlich-Königliches Deutsches Staats-Realgymnasium Prag',
      persons: new Set(['624']),
      places: new Set([]),
      institutions: new Set([]),
    },
  ],
  [
    '1135',
    {
      kind: 'institution',
      id: '1135',
      label: 'Kurt Wolff Verlag',
      persons: new Set(['624']),
      places: new Set([]),
      institutions: new Set([]),
    },
  ],
  [
    '1487',
    {
      kind: 'institution',
      id: '1487',
      label: 'Viking Press',
      persons: new Set(['624', '406']),
      places: new Set([]),
      institutions: new Set([]),
    },
  ],
  [
    '7166',
    {
      kind: 'institution',
      id: '7166',
      label: 'Imperial Palace Hotel, Santa Magherita Ligure',
      persons: new Set(['624']),
      places: new Set([]),
      institutions: new Set([]),
    },
  ],
  [
    '1718',
    {
      kind: 'institution',
      id: '1718',
      label: 'Hotel Bristol, Vienna',
      persons: new Set(['672']),
      places: new Set([]),
      institutions: new Set([]),
    },
  ],
  [
    '1722',
    {
      kind: 'institution',
      id: '1722',
      label: 'Schloss Cobenzl',
      persons: new Set(['672']),
      places: new Set([]),
      institutions: new Set([]),
    },
  ],
  [
    '1899',
    {
      kind: 'institution',
      id: '1899',
      label: 'Oberlin College',
      persons: new Set(['672']),
      places: new Set([]),
      institutions: new Set([]),
    },
  ],
  [
    '2173',
    {
      kind: 'institution',
      id: '2173',
      label: 'American Academy in Rome',
      persons: new Set(['672']),
      places: new Set([]),
      institutions: new Set([]),
    },
  ],
  [
    '2354',
    {
      kind: 'institution',
      id: '2354',
      label: 'Pulitzer Prize',
      persons: new Set(['672']),
      places: new Set([]),
      institutions: new Set([]),
    },
  ],
  [
    '2358',
    {
      kind: 'institution',
      id: '2358',
      label: 'Yale University',
      persons: new Set(['672']),
      places: new Set([]),
      institutions: new Set([]),
    },
  ],
  [
    '2366',
    {
      kind: 'institution',
      id: '2366',
      label: 'Princeton University',
      persons: new Set(['672', '280']),
      places: new Set([]),
      institutions: new Set([]),
    },
  ],
  [
    '2370',
    {
      kind: 'institution',
      id: '2370',
      label: 'Lawrenceville School',
      persons: new Set(['672']),
      places: new Set([]),
      institutions: new Set([]),
    },
  ],
  [
    '5009',
    {
      kind: 'institution',
      id: '5009',
      label: 'United States Army, Air Forces',
      persons: new Set(['672']),
      places: new Set([]),
      institutions: new Set([]),
    },
  ],
  [
    '6285',
    {
      kind: 'institution',
      id: '6285',
      label: 'Hotel Bayerischer Hof',
      persons: new Set(['672']),
      places: new Set([]),
      institutions: new Set([]),
    },
  ],
  [
    '3835',
    {
      kind: 'institution',
      id: '3835',
      label: 'University of North Carolina',
      persons: new Set(['507']),
      places: new Set([]),
      institutions: new Set([]),
    },
  ],
  [
    '4444',
    {
      kind: 'institution',
      id: '4444',
      label: 'New York University',
      persons: new Set(['507', '280']),
      places: new Set([]),
      institutions: new Set([]),
    },
  ],
  [
    '6261',
    {
      kind: 'institution',
      id: '6261',
      label: 'Hotel Höller',
      persons: new Set(['507']),
      places: new Set([]),
      institutions: new Set([]),
    },
  ],
  [
    '1286',
    {
      kind: 'institution',
      id: '1286',
      label: 'Kunsthistorisches Museum Wien',
      persons: new Set(['507', '504']),
      places: new Set([]),
      institutions: new Set([]),
    },
  ],
  [
    '1378',
    {
      kind: 'institution',
      id: '1378',
      label: 'Kabarett Simpl',
      persons: new Set(['507']),
      places: new Set([]),
      institutions: new Set([]),
    },
  ],
  [
    '1205',
    {
      kind: 'institution',
      id: '1205',
      label: 'Theater Kiel',
      persons: new Set(['633']),
      places: new Set([]),
      institutions: new Set([]),
    },
  ],
  [
    '1227',
    {
      kind: 'institution',
      id: '1227',
      label: 'USA. Office of Strategic Services',
      persons: new Set(['633']),
      places: new Set([]),
      institutions: new Set([]),
    },
  ],
  [
    '1871',
    {
      kind: 'institution',
      id: '1871',
      label: 'British citizenship',
      persons: new Set(['509']),
      places: new Set([]),
      institutions: new Set([]),
    },
  ],
  [
    '6879',
    {
      kind: 'institution',
      id: '6879',
      label: 'Hotel Bellevue, Vienna',
      persons: new Set(['509']),
      places: new Set([]),
      institutions: new Set([]),
    },
  ],
  [
    '696',
    {
      kind: 'institution',
      id: '696',
      label: 'Colorado College, Colorado Springs',
      persons: new Set(['616']),
      places: new Set([]),
      institutions: new Set([]),
    },
  ],
  [
    '2638',
    {
      kind: 'institution',
      id: '2638',
      label: 'Information Services Branch',
      persons: new Set(['616']),
      places: new Set([]),
      institutions: new Set([]),
    },
  ],
  [
    '2819',
    {
      kind: 'institution',
      id: '2819',
      label: 'Radio-Verkehrs-AG (RAVAG)',
      persons: new Set(['616']),
      places: new Set([]),
      institutions: new Set([]),
    },
  ],
  [
    '7580',
    {
      kind: 'institution',
      id: '7580',
      label: 'European Film Fund',
      persons: new Set(['616', '7595', '1063']),
      places: new Set([]),
      institutions: new Set([]),
    },
  ],
  [
    '7718',
    {
      kind: 'institution',
      id: '7718',
      label: 'Austrian Federal Ministry for Commerce and Transport',
      persons: new Set(['616']),
      places: new Set([]),
      institutions: new Set([]),
    },
  ],
  [
    '5968',
    {
      kind: 'institution',
      id: '5968',
      label: 'League of Nations',
      persons: new Set(['360']),
      places: new Set([]),
      institutions: new Set([]),
    },
  ],
  [
    '5972',
    {
      kind: 'institution',
      id: '5972',
      label: 'News Chronicle (London)',
      persons: new Set(['360']),
      places: new Set([]),
      institutions: new Set([]),
    },
  ],
  [
    '2915',
    {
      kind: 'institution',
      id: '2915',
      label: 'Socialist Party of America',
      persons: new Set(['389']),
      places: new Set([]),
      institutions: new Set([]),
    },
  ],
  [
    '2916',
    {
      kind: 'institution',
      id: '2916',
      label: 'Communist Party USA',
      persons: new Set(['389']),
      places: new Set([]),
      institutions: new Set([]),
    },
  ],
  [
    '2926',
    {
      kind: 'institution',
      id: '2926',
      label: 'New Masses',
      persons: new Set(['389']),
      places: new Set([]),
      institutions: new Set([]),
    },
  ],
  [
    '2928',
    {
      kind: 'institution',
      id: '2928',
      label: 'The Partisan Review',
      persons: new Set(['389']),
      places: new Set([]),
      institutions: new Set([]),
    },
  ],
  [
    '2956',
    {
      kind: 'institution',
      id: '2956',
      label: 'American Civil Liberties Union',
      persons: new Set(['389']),
      places: new Set([]),
      institutions: new Set([]),
    },
  ],
  [
    '2968',
    {
      kind: 'institution',
      id: '2968',
      label: 'TASS Office New York',
      persons: new Set(['389']),
      places: new Set([]),
      institutions: new Set([]),
    },
  ],
  [
    '6736',
    {
      kind: 'institution',
      id: '6736',
      label: 'United Press International',
      persons: new Set(['6561']),
      places: new Set([]),
      institutions: new Set([]),
    },
  ],
  [
    '3113',
    {
      kind: 'institution',
      id: '3113',
      label: 'Wofford College, Spartanburg, SC',
      persons: new Set(['6561']),
      places: new Set([]),
      institutions: new Set([]),
    },
  ],
  [
    '6774',
    {
      kind: 'institution',
      id: '6774',
      label: 'Amepress',
      persons: new Set(['6561']),
      places: new Set([]),
      institutions: new Set([]),
    },
  ],
  [
    '5327',
    {
      kind: 'institution',
      id: '5327',
      label: 'Amerikanische Kinderhilfsaktion',
      persons: new Set(['2410']),
      places: new Set([]),
      institutions: new Set([]),
    },
  ],
  [
    '5334',
    {
      kind: 'institution',
      id: '5334',
      label: "Pediatric Clinic of Vienna's General Hospital",
      persons: new Set(['2410']),
      places: new Set([]),
      institutions: new Set([]),
    },
  ],
  [
    '3104',
    {
      kind: 'institution',
      id: '3104',
      label: 'Johns Hopkins University',
      persons: new Set(['2410']),
      places: new Set([]),
      institutions: new Set([]),
    },
  ],
  [
    '7358',
    {
      kind: 'institution',
      id: '7358',
      label: 'Institut für Anatomie (Wien)',
      persons: new Set(['6754']),
      places: new Set([]),
      institutions: new Set([]),
    },
  ],
  [
    '2328',
    {
      kind: 'institution',
      id: '2328',
      label: 'Spanische Reitschule (Wien)',
      persons: new Set(['504']),
      places: new Set([]),
      institutions: new Set([]),
    },
  ],
  [
    '2402',
    {
      kind: 'institution',
      id: '2402',
      label: 'Contact',
      persons: new Set(['504']),
      places: new Set([]),
      institutions: new Set([]),
    },
  ],
  [
    '5983',
    {
      kind: 'institution',
      id: '5983',
      label: 'Café Edison',
      persons: new Set(['504']),
      places: new Set([]),
      institutions: new Set([]),
    },
  ],
  [
    '6294',
    {
      kind: 'institution',
      id: '6294',
      label: 'Pennsylvania Academy of the Fine Arts',
      persons: new Set(['401']),
      places: new Set([]),
      institutions: new Set([]),
    },
  ],
  [
    '1420',
    {
      kind: 'institution',
      id: '1420',
      label: 'Hotel Imperial',
      persons: new Set(['401']),
      places: new Set([]),
      institutions: new Set([]),
    },
  ],
  [
    '1409',
    {
      kind: 'institution',
      id: '1409',
      label: 'Wellesley College',
      persons: new Set(['7378']),
      places: new Set([]),
      institutions: new Set([]),
    },
  ],
  [
    '1413',
    {
      kind: 'institution',
      id: '1413',
      label: 'University of Oxford',
      persons: new Set(['7378']),
      places: new Set([]),
      institutions: new Set([]),
    },
  ],
  [
    '7392',
    {
      kind: 'institution',
      id: '7392',
      label: 'Revolutionary Socialists',
      persons: new Set(['7378', '1397']),
      places: new Set([]),
      institutions: new Set([]),
    },
  ],
  [
    '4297',
    {
      kind: 'institution',
      id: '4297',
      label: 'The Manchester Guardian (since 1959 The Guardian)',
      persons: new Set(['387']),
      places: new Set([]),
      institutions: new Set([]),
    },
  ],
  [
    '4298',
    {
      kind: 'institution',
      id: '4298',
      label: 'The American Mercury',
      persons: new Set(['387', '1540']),
      places: new Set([]),
      institutions: new Set([]),
    },
  ],
  [
    '4305',
    {
      kind: 'institution',
      id: '4305',
      label: 'Die Neue Zeitung',
      persons: new Set(['387']),
      places: new Set([]),
      institutions: new Set([]),
    },
  ],
  [
    '6383',
    {
      kind: 'institution',
      id: '6383',
      label: 'Philadelphia Inquirer',
      persons: new Set(['387']),
      places: new Set([]),
      institutions: new Set([]),
    },
  ],
  [
    '6385',
    {
      kind: 'institution',
      id: '6385',
      label: 'New York Daily News',
      persons: new Set(['387']),
      places: new Set([]),
      institutions: new Set([]),
    },
  ],
  [
    '6583',
    {
      kind: 'institution',
      id: '6583',
      label: '-',
      persons: new Set(['387']),
      places: new Set([]),
      institutions: new Set([]),
    },
  ],
  [
    '1470',
    {
      kind: 'institution',
      id: '1470',
      label: 'Daily Telegraph',
      persons: new Set(['392']),
      places: new Set([]),
      institutions: new Set([]),
    },
  ],
  [
    '803',
    {
      kind: 'institution',
      id: '803',
      label: 'Film-, Theater-, und Musikabteilung der US-Botschaft in Wien',
      persons: new Set(['610']),
      places: new Set([]),
      institutions: new Set([]),
    },
  ],
  [
    '1371',
    {
      kind: 'institution',
      id: '1371',
      label: 'Akademie für Musik und Darstellende Kunst (Vienna)',
      persons: new Set(['610', '2699', '2689']),
      places: new Set([]),
      institutions: new Set([]),
    },
  ],
  [
    '7250',
    {
      kind: 'institution',
      id: '7250',
      label: 'Cosmopol-Film',
      persons: new Set(['610']),
      places: new Set([]),
      institutions: new Set([]),
    },
  ],
  [
    '1480',
    {
      kind: 'institution',
      id: '1480',
      label: 'B. W. Huebsch',
      persons: new Set(['406']),
      places: new Set([]),
      institutions: new Set([]),
    },
  ],
  [
    '6313',
    {
      kind: 'institution',
      id: '6313',
      label: 'Die praktische Berlinerin',
      persons: new Set(['413']),
      places: new Set([]),
      institutions: new Set([]),
    },
  ],
  [
    '2731',
    {
      kind: 'institution',
      id: '2731',
      label: 'Paramount Pictures Corporation',
      persons: new Set(['2699', '2703']),
      places: new Set([]),
      institutions: new Set([]),
    },
  ],
  [
    '718',
    {
      kind: 'institution',
      id: '718',
      label: 'Roman Catholic',
      persons: new Set(['540', '640']),
      places: new Set([]),
      institutions: new Set([]),
    },
  ],
  [
    '6802',
    {
      kind: 'institution',
      id: '6802',
      label: 'Die Fackel',
      persons: new Set(['540']),
      places: new Set([]),
      institutions: new Set([]),
    },
  ],
  [
    '6807',
    {
      kind: 'institution',
      id: '6807',
      label: 'Franz-Josephs-Gymnasium',
      persons: new Set(['540']),
      places: new Set([]),
      institutions: new Set([]),
    },
  ],
  [
    '6846',
    {
      kind: 'institution',
      id: '6846',
      label: 'Kaiser-Wilhelm-Institut für Chemie',
      persons: new Set(['6522']),
      places: new Set([]),
      institutions: new Set([]),
    },
  ],
  [
    '6842',
    {
      kind: 'institution',
      id: '6842',
      label: 'University of Canterbury, NZ',
      persons: new Set(['104']),
      places: new Set([]),
      institutions: new Set([]),
    },
  ],
  [
    '6535',
    {
      kind: 'institution',
      id: '6535',
      label: 'British Columbia Medical Association',
      persons: new Set(['6533']),
      places: new Set([]),
      institutions: new Set([]),
    },
  ],
  [
    '6537',
    {
      kind: 'institution',
      id: '6537',
      label: 'Canadian Medical Association',
      persons: new Set(['6533']),
      places: new Set([]),
      institutions: new Set([]),
    },
  ],
  [
    '7223',
    {
      kind: 'institution',
      id: '7223',
      label: 'Akademie der Künste',
      persons: new Set(['2707']),
      places: new Set([]),
      institutions: new Set([]),
    },
  ],
  [
    '7226',
    {
      kind: 'institution',
      id: '7226',
      label: 'Staatliches Konservatorium',
      persons: new Set(['2707']),
      places: new Set([]),
      institutions: new Set([]),
    },
  ],
  [
    '7024',
    {
      kind: 'institution',
      id: '7024',
      label: 'University of California Los Angeles',
      persons: new Set(['471']),
      places: new Set([]),
      institutions: new Set([]),
    },
  ],
  [
    '2711',
    {
      kind: 'institution',
      id: '2711',
      label: 'Ronacher Vienna',
      persons: new Set(['2689']),
      places: new Set([]),
      institutions: new Set([]),
    },
  ],
  [
    '2720',
    {
      kind: 'institution',
      id: '2720',
      label: 'RKO Pictures, Hollywood',
      persons: new Set(['2689', '2703']),
      places: new Set([]),
      institutions: new Set([]),
    },
  ],
  [
    '2727',
    {
      kind: 'institution',
      id: '2727',
      label: 'Selznick International Orchestra',
      persons: new Set(['2689']),
      places: new Set([]),
      institutions: new Set([]),
    },
  ],
  [
    '7695',
    {
      kind: 'institution',
      id: '7695',
      label: 'Ziegfeld Follies',
      persons: new Set(['2689']),
      places: new Set([]),
      institutions: new Set([]),
    },
  ],
  [
    '7287',
    {
      kind: 'institution',
      id: '7287',
      label: 'University of Southern California',
      persons: new Set(['2703']),
      places: new Set([]),
      institutions: new Set([]),
    },
  ],
  [
    '7301',
    {
      kind: 'institution',
      id: '7301',
      label: 'Twentieth Century Fox Film Corporation, Hollywood',
      persons: new Set(['2703', '604']),
      places: new Set([]),
      institutions: new Set([]),
    },
  ],
  [
    '4107',
    {
      kind: 'institution',
      id: '4107',
      label: 'Stanford Center for the Advanced Study of the Behavioral Sciences',
      persons: new Set(['7404']),
      places: new Set([]),
      institutions: new Set([]),
    },
  ],
  [
    '6433',
    {
      kind: 'institution',
      id: '6433',
      label: 'Faculty of Political Science of Columbia University',
      persons: new Set(['7404']),
      places: new Set([]),
      institutions: new Set([]),
    },
  ],
  [
    '7401',
    {
      kind: 'institution',
      id: '7401',
      label: 'Bureau of Applied Social Research',
      persons: new Set(['7404']),
      places: new Set([]),
      institutions: new Set([]),
    },
  ],
  [
    '7411',
    {
      kind: 'institution',
      id: '7411',
      label: 'Radio Research Project (Princeton University)',
      persons: new Set(['7404', '161']),
      places: new Set([]),
      institutions: new Set([]),
    },
  ],
  [
    '7437',
    {
      kind: 'institution',
      id: '7437',
      label: 'Research Center, University of Newark',
      persons: new Set(['7404']),
      places: new Set([]),
      institutions: new Set([]),
    },
  ],
  [
    '7204',
    {
      kind: 'institution',
      id: '7204',
      label: 'Rockefeller Foundation',
      persons: new Set(['7404', '280']),
      places: new Set([]),
      institutions: new Set([]),
    },
  ],
  [
    '3221',
    {
      kind: 'institution',
      id: '3221',
      label: 'Université Paris-Sorbonne',
      persons: new Set(['7404']),
      places: new Set([]),
      institutions: new Set([]),
    },
  ],
  [
    '7485',
    {
      kind: 'institution',
      id: '7485',
      label: "Maison des sciences de l'homme",
      persons: new Set(['7404']),
      places: new Set([]),
      institutions: new Set([]),
    },
  ],
  [
    '7508',
    {
      kind: 'institution',
      id: '7508',
      label: 'Institut für Höhere Studien - Institute for Advanced Studies (IHS)',
      persons: new Set(['7404', '280']),
      places: new Set([]),
      institutions: new Set([]),
    },
  ],
  [
    '7972',
    {
      kind: 'institution',
      id: '7972',
      label: 'Insitute of Psychology, University of Vienna',
      persons: new Set(['7404']),
      places: new Set([]),
      institutions: new Set([]),
    },
  ],
  [
    '7975',
    {
      kind: 'institution',
      id: '7975',
      label: 'American Sociological Association',
      persons: new Set(['7404']),
      places: new Set([]),
      institutions: new Set([]),
    },
  ],
  [
    '7505',
    {
      kind: 'institution',
      id: '7505',
      label: 'Wiener Konjunkturforschungsinstitut',
      persons: new Set(['280']),
      places: new Set([]),
      institutions: new Set([]),
    },
  ],
  [
    '1263',
    {
      kind: 'institution',
      id: '1263',
      label: "St. John's University Shanghai",
      persons: new Set(['649']),
      places: new Set([]),
      institutions: new Set([]),
    },
  ],
  [
    '1265',
    {
      kind: 'institution',
      id: '1265',
      label: 'University of California Berkeley',
      persons: new Set(['649']),
      places: new Set([]),
      institutions: new Set([]),
    },
  ],
  [
    '2773',
    {
      kind: 'institution',
      id: '2773',
      label: 'Institut Wiener Kreis',
      persons: new Set(['649']),
      places: new Set([]),
      institutions: new Set([]),
    },
  ],
  [
    '7913',
    {
      kind: 'institution',
      id: '7913',
      label: 'Millersville University of Pennsylvania',
      persons: new Set(['649']),
      places: new Set([]),
      institutions: new Set([]),
    },
  ],
  [
    '7750',
    {
      kind: 'institution',
      id: '7750',
      label: 'University of California, Davis',
      persons: new Set(['649']),
      places: new Set([]),
      institutions: new Set([]),
    },
  ],
  [
    '1274',
    {
      kind: 'institution',
      id: '1274',
      label: 'Café Hummel',
      persons: new Set(['649']),
      places: new Set([]),
      institutions: new Set([]),
    },
  ],
  [
    '7907',
    {
      kind: 'institution',
      id: '7907',
      label: 'Mills College',
      persons: new Set(['649']),
      places: new Set([]),
      institutions: new Set([]),
    },
  ],
  [
    '7911',
    {
      kind: 'institution',
      id: '7911',
      label: 'City University of New York',
      persons: new Set(['649']),
      places: new Set([]),
      institutions: new Set([]),
    },
  ],
  [
    '7922',
    {
      kind: 'institution',
      id: '7922',
      label: 'Universität Kassel',
      persons: new Set(['649']),
      places: new Set([]),
      institutions: new Set([]),
    },
  ],
  [
    '7936',
    {
      kind: 'institution',
      id: '7936',
      label: 'Fulbright Program',
      persons: new Set(['649']),
      places: new Set([]),
      institutions: new Set([]),
    },
  ],
  [
    '8132',
    {
      kind: 'institution',
      id: '8132',
      label: 'Gymnasium Albertgasse',
      persons: new Set(['649']),
      places: new Set([]),
      institutions: new Set([]),
    },
  ],
  [
    '6671',
    {
      kind: 'institution',
      id: '6671',
      label: 'Embassy of the United States in Vienna',
      persons: new Set(['4290']),
      places: new Set([]),
      institutions: new Set([]),
    },
  ],
  [
    '7384',
    {
      kind: 'institution',
      id: '7384',
      label: 'Auslandsvertretung der österreichischen Sozialisten (AVOES)',
      persons: new Set(['1397']),
      places: new Set([]),
      institutions: new Set([]),
    },
  ],
  [
    '7398',
    {
      kind: 'institution',
      id: '7398',
      label: 'International Rescue Committee (IRC)',
      persons: new Set(['1397']),
      places: new Set([]),
      institutions: new Set([]),
    },
  ],
  [
    '7646',
    {
      kind: 'institution',
      id: '7646',
      label: 'Österreichische Kinderfreunde (St. Veit a. d. Glan)',
      persons: new Set(['1397']),
      places: new Set([]),
      institutions: new Set([]),
    },
  ],
  [
    '7653',
    {
      kind: 'institution',
      id: '7653',
      label: 'SDAP (St. Veit a. d. Glan)',
      persons: new Set(['1397']),
      places: new Set([]),
      institutions: new Set([]),
    },
  ],
  [
    '7660',
    {
      kind: 'institution',
      id: '7660',
      label: 'American Friends of Vietnam',
      persons: new Set(['1397']),
      places: new Set([]),
      institutions: new Set([]),
    },
  ],
  [
    '6161',
    {
      kind: 'institution',
      id: '6161',
      label: 'Grand Hotel Gardone Riviera, Lake Garda',
      persons: new Set(['11']),
      places: new Set([]),
      institutions: new Set([]),
    },
  ],
  [
    '6174',
    {
      kind: 'institution',
      id: '6174',
      label: 'Harvard Advocate',
      persons: new Set(['355']),
      places: new Set([]),
      institutions: new Set([]),
    },
  ],
  [
    '6179',
    {
      kind: 'institution',
      id: '6179',
      label: 'American Field Service',
      persons: new Set(['355']),
      places: new Set([]),
      institutions: new Set([]),
    },
  ],
  [
    '2550',
    {
      kind: 'institution',
      id: '2550',
      label: 'Secession',
      persons: new Set(['355']),
      places: new Set([]),
      institutions: new Set([]),
    },
  ],
  [
    '1173',
    {
      kind: 'institution',
      id: '1173',
      label: 'Verlag Die Fackel (Wien)',
      persons: new Set(['604']),
      places: new Set([]),
      institutions: new Set([]),
    },
  ],
  [
    '1176',
    {
      kind: 'institution',
      id: '1176',
      label: 'Schauspielhaus Dresden',
      persons: new Set(['604']),
      places: new Set([]),
      institutions: new Set([]),
    },
  ],
  [
    '6456',
    {
      kind: 'institution',
      id: '6456',
      label: 'Kunst, Literatur und Musik',
      persons: new Set(['604']),
      places: new Set([]),
      institutions: new Set([]),
    },
  ],
  [
    '6459',
    {
      kind: 'institution',
      id: '6459',
      label: 'Books Abroad',
      persons: new Set(['604']),
      places: new Set([]),
      institutions: new Set([]),
    },
  ],
  [
    '7308',
    {
      kind: 'institution',
      id: '7308',
      label: 'Freie Volksbühne Wien',
      persons: new Set(['604']),
      places: new Set([]),
      institutions: new Set([]),
    },
  ],
  [
    '7313',
    {
      kind: 'institution',
      id: '7313',
      label: 'Düsseldorfer Schauspielhaus',
      persons: new Set(['604']),
      places: new Set([]),
      institutions: new Set([]),
    },
  ],
  [
    '7322',
    {
      kind: 'institution',
      id: '7322',
      label: 'Akademietheater Wien',
      persons: new Set(['604']),
      places: new Set([]),
      institutions: new Set([]),
    },
  ],
  [
    '7325',
    {
      kind: 'institution',
      id: '7325',
      label: 'Gaumont British Picture Corporation (London)',
      persons: new Set(['604']),
      places: new Set([]),
      institutions: new Set([]),
    },
  ],
  [
    '7667',
    {
      kind: 'institution',
      id: '7667',
      label: 'Café Central (Wien)',
      persons: new Set(['604']),
      places: new Set([]),
      institutions: new Set([]),
    },
  ],
  [
    '7672',
    {
      kind: 'institution',
      id: '7672',
      label: 'Aurora Verlag',
      persons: new Set(['604']),
      places: new Set([]),
      institutions: new Set([]),
    },
  ],
  [
    '7681',
    {
      kind: 'institution',
      id: '7681',
      label: 'Volksschule Zieglergasse',
      persons: new Set(['604']),
      places: new Set([]),
      institutions: new Set([]),
    },
  ],
  [
    '7684',
    {
      kind: 'institution',
      id: '7684',
      label: 'Amerlinggymnasium',
      persons: new Set(['604']),
      places: new Set([]),
      institutions: new Set([]),
    },
  ],
])
