name: Build and deploy Docker image

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  push:
    branches:
      - main

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to the Container registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          build-args: |
            NEXT_PUBLIC_BASE_URL=https://ica-vis.acdh-dev.oeaw.ac.at
            NEXT_PUBLIC_MOCK_API=disabled
            NEXT_PUBLIC_REDMINE_ID=20399
            NEXT_PUBLIC_MATOMO_BASE_URL=https://matomo.acdh.oeaw.ac.at
            NEXT_PUBLIC_MATOMO_ID=225
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Deploy to cluster
        env:
          RANCHER_PROJECT_ID: c-zdbh8:p-hzftn
          RANCHER_DEPLOYMENT: ica:ica-website
        run: |
          curl \
            -X POST \
            -H "Authorization: Bearer ${{ secrets.RANCHER_API_TOKEN }}" \
            'https://rancher.acdh-dev.oeaw.ac.at/v3/project/${{ env.RANCHER_PROJECT_ID }}/workloads/deployment:${{ env.RANCHER_DEPLOYMENT }}?action=redeploy'
