name: Validate

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  pull_request:
    branches:
      - main

jobs:
  validate:
    runs-on: ${{ matrix.os }}

    timeout-minutes: 60

    strategy:
      fail-fast: true
      matrix:
        node-version:
          - 18.x
        os:
          - ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      # necessary because actions/setup-node does not yet support corepack yet
      # @see https://github.com/actions/setup-node/issues/531
      - name: Install pnpm
        uses: pnpm/action-setup@v2

      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Format
        run: pnpm run format:check

      - name: Lint
        run: pnpm run lint:check

      - name: Typecheck
        run: pnpm run types:check

      - name: Unit tests
        run: pnpm run test
